//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/guava/sources/com/google/common/io/CharSequenceReader.java
//

#include <j2objc/J2ObjC_header.h>

#pragma push_macro("ComGoogleCommonIoCharSequenceReader_INCLUDE_ALL")
#if ComGoogleCommonIoCharSequenceReader_RESTRICT
#define ComGoogleCommonIoCharSequenceReader_INCLUDE_ALL 0
#else
#define ComGoogleCommonIoCharSequenceReader_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoCharSequenceReader_RESTRICT

#if !defined (_ComGoogleCommonIoCharSequenceReader_) && (ComGoogleCommonIoCharSequenceReader_INCLUDE_ALL || ComGoogleCommonIoCharSequenceReader_INCLUDE)
#define _ComGoogleCommonIoCharSequenceReader_

#define JavaIoReader_RESTRICT 1
#define JavaIoReader_INCLUDE 1
#include <j2objc/java/io/Reader.h>

@class IOSCharArray;
@class JavaNioCharBuffer;
@protocol JavaLangCharSequence;

@interface ComGoogleCommonIoCharSequenceReader : JavaIoReader

#pragma mark Public

- (instancetype)initWithJavaLangCharSequence:(id<JavaLangCharSequence>)seq;

- (void)close;

- (void)markWithInt:(jint)readAheadLimit;

- (jboolean)markSupported;

- (jint)read;

- (jint)readWithCharArray:(IOSCharArray *)cbuf
                  withInt:(jint)off
                  withInt:(jint)len;

- (jint)readWithJavaNioCharBuffer:(JavaNioCharBuffer *)target;

- (jboolean)ready;

- (void)reset;

- (jlong)skipWithLong:(jlong)n;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoCharSequenceReader)

FOUNDATION_EXPORT void ComGoogleCommonIoCharSequenceReader_initWithJavaLangCharSequence_(ComGoogleCommonIoCharSequenceReader *self, id<JavaLangCharSequence> seq);

FOUNDATION_EXPORT ComGoogleCommonIoCharSequenceReader *new_ComGoogleCommonIoCharSequenceReader_initWithJavaLangCharSequence_(id<JavaLangCharSequence> seq) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoCharSequenceReader)

#endif

#pragma pop_macro("ComGoogleCommonIoCharSequenceReader_INCLUDE_ALL")
