//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/guava/sources/com/google/common/io/Closer.java
//

#include <j2objc/J2ObjC_header.h>

#pragma push_macro("ComGoogleCommonIoCloser_INCLUDE_ALL")
#if ComGoogleCommonIoCloser_RESTRICT
#define ComGoogleCommonIoCloser_INCLUDE_ALL 0
#else
#define ComGoogleCommonIoCloser_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoCloser_RESTRICT
#if ComGoogleCommonIoCloser_SuppressingSuppressor_INCLUDE
#define ComGoogleCommonIoCloser_Suppressor_INCLUDE 1
#endif
#if ComGoogleCommonIoCloser_LoggingSuppressor_INCLUDE
#define ComGoogleCommonIoCloser_Suppressor_INCLUDE 1
#endif

#if !defined (_ComGoogleCommonIoCloser_) && (ComGoogleCommonIoCloser_INCLUDE_ALL || ComGoogleCommonIoCloser_INCLUDE)
#define _ComGoogleCommonIoCloser_

#define JavaIoCloseable_RESTRICT 1
#define JavaIoCloseable_INCLUDE 1
#include <j2objc/java/io/Closeable.h>

@class IOSClass;
@class JavaLangRuntimeException;
@class JavaLangThrowable;
@protocol ComGoogleCommonIoCloser_Suppressor;

@interface ComGoogleCommonIoCloser : NSObject < JavaIoCloseable > {
 @public
  id<ComGoogleCommonIoCloser_Suppressor> suppressor_;
}

#pragma mark Public

- (void)close;

+ (ComGoogleCommonIoCloser *)create;

- (id)register__WithJavaIoCloseable:(id<JavaIoCloseable>)closeable;

- (JavaLangRuntimeException *)rethrowWithJavaLangThrowable:(JavaLangThrowable *)e;

- (JavaLangRuntimeException *)rethrowWithJavaLangThrowable:(JavaLangThrowable *)e
                                              withIOSClass:(IOSClass *)declaredType1
                                              withIOSClass:(IOSClass *)declaredType2;

- (JavaLangRuntimeException *)rethrowWithJavaLangThrowable:(JavaLangThrowable *)e
                                              withIOSClass:(IOSClass *)declaredType;

#pragma mark Package-Private

- (instancetype)initWithComGoogleCommonIoCloser_Suppressor:(id<ComGoogleCommonIoCloser_Suppressor>)suppressor;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonIoCloser)

J2OBJC_FIELD_SETTER(ComGoogleCommonIoCloser, suppressor_, id<ComGoogleCommonIoCloser_Suppressor>)

FOUNDATION_EXPORT ComGoogleCommonIoCloser *ComGoogleCommonIoCloser_create();

FOUNDATION_EXPORT void ComGoogleCommonIoCloser_initWithComGoogleCommonIoCloser_Suppressor_(ComGoogleCommonIoCloser *self, id<ComGoogleCommonIoCloser_Suppressor> suppressor);

FOUNDATION_EXPORT ComGoogleCommonIoCloser *new_ComGoogleCommonIoCloser_initWithComGoogleCommonIoCloser_Suppressor_(id<ComGoogleCommonIoCloser_Suppressor> suppressor) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoCloser)

#endif

#if !defined (_ComGoogleCommonIoCloser_Suppressor_) && (ComGoogleCommonIoCloser_INCLUDE_ALL || ComGoogleCommonIoCloser_Suppressor_INCLUDE)
#define _ComGoogleCommonIoCloser_Suppressor_

@class JavaLangThrowable;
@protocol JavaIoCloseable;

@protocol ComGoogleCommonIoCloser_Suppressor < NSObject, JavaObject >

- (void)suppressWithJavaIoCloseable:(id<JavaIoCloseable>)closeable
              withJavaLangThrowable:(JavaLangThrowable *)thrown
              withJavaLangThrowable:(JavaLangThrowable *)suppressed;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoCloser_Suppressor)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoCloser_Suppressor)

#endif

#if !defined (_ComGoogleCommonIoCloser_LoggingSuppressor_) && (ComGoogleCommonIoCloser_INCLUDE_ALL || ComGoogleCommonIoCloser_LoggingSuppressor_INCLUDE)
#define _ComGoogleCommonIoCloser_LoggingSuppressor_

@class JavaLangThrowable;
@protocol JavaIoCloseable;

@interface ComGoogleCommonIoCloser_LoggingSuppressor : NSObject < ComGoogleCommonIoCloser_Suppressor >

#pragma mark Public

- (void)suppressWithJavaIoCloseable:(id<JavaIoCloseable>)closeable
              withJavaLangThrowable:(JavaLangThrowable *)thrown
              withJavaLangThrowable:(JavaLangThrowable *)suppressed;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonIoCloser_LoggingSuppressor)

FOUNDATION_EXPORT ComGoogleCommonIoCloser_LoggingSuppressor *ComGoogleCommonIoCloser_LoggingSuppressor_INSTANCE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonIoCloser_LoggingSuppressor, INSTANCE_, ComGoogleCommonIoCloser_LoggingSuppressor *)

FOUNDATION_EXPORT void ComGoogleCommonIoCloser_LoggingSuppressor_init(ComGoogleCommonIoCloser_LoggingSuppressor *self);

FOUNDATION_EXPORT ComGoogleCommonIoCloser_LoggingSuppressor *new_ComGoogleCommonIoCloser_LoggingSuppressor_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoCloser_LoggingSuppressor)

#endif

#if !defined (_ComGoogleCommonIoCloser_SuppressingSuppressor_) && (ComGoogleCommonIoCloser_INCLUDE_ALL || ComGoogleCommonIoCloser_SuppressingSuppressor_INCLUDE)
#define _ComGoogleCommonIoCloser_SuppressingSuppressor_

@class JavaLangReflectMethod;
@class JavaLangThrowable;
@protocol JavaIoCloseable;

@interface ComGoogleCommonIoCloser_SuppressingSuppressor : NSObject < ComGoogleCommonIoCloser_Suppressor >

#pragma mark Public

- (void)suppressWithJavaIoCloseable:(id<JavaIoCloseable>)closeable
              withJavaLangThrowable:(JavaLangThrowable *)thrown
              withJavaLangThrowable:(JavaLangThrowable *)suppressed;

#pragma mark Package-Private

- (instancetype)init;

+ (jboolean)isAvailable;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonIoCloser_SuppressingSuppressor)

FOUNDATION_EXPORT ComGoogleCommonIoCloser_SuppressingSuppressor *ComGoogleCommonIoCloser_SuppressingSuppressor_INSTANCE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonIoCloser_SuppressingSuppressor, INSTANCE_, ComGoogleCommonIoCloser_SuppressingSuppressor *)

FOUNDATION_EXPORT JavaLangReflectMethod *ComGoogleCommonIoCloser_SuppressingSuppressor_addSuppressed_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonIoCloser_SuppressingSuppressor, addSuppressed_, JavaLangReflectMethod *)

FOUNDATION_EXPORT jboolean ComGoogleCommonIoCloser_SuppressingSuppressor_isAvailable();

FOUNDATION_EXPORT void ComGoogleCommonIoCloser_SuppressingSuppressor_init(ComGoogleCommonIoCloser_SuppressingSuppressor *self);

FOUNDATION_EXPORT ComGoogleCommonIoCloser_SuppressingSuppressor *new_ComGoogleCommonIoCloser_SuppressingSuppressor_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoCloser_SuppressingSuppressor)

#endif

#pragma pop_macro("ComGoogleCommonIoCloser_INCLUDE_ALL")
