//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/guava/sources/com/google/common/io/FileWriteMode.java
//

#include <j2objc/J2ObjC_header.h>

#pragma push_macro("ComGoogleCommonIoFileWriteMode_INCLUDE_ALL")
#if ComGoogleCommonIoFileWriteMode_RESTRICT
#define ComGoogleCommonIoFileWriteMode_INCLUDE_ALL 0
#else
#define ComGoogleCommonIoFileWriteMode_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoFileWriteMode_RESTRICT

#if !defined (_ComGoogleCommonIoFileWriteModeEnum_) && (ComGoogleCommonIoFileWriteMode_INCLUDE_ALL || ComGoogleCommonIoFileWriteModeEnum_INCLUDE)
#define _ComGoogleCommonIoFileWriteModeEnum_

#define JavaLangEnum_RESTRICT 1
#define JavaLangEnum_INCLUDE 1
#include <j2objc/java/lang/Enum.h>

typedef NS_ENUM(NSUInteger, ComGoogleCommonIoFileWriteMode) {
  ComGoogleCommonIoFileWriteMode_APPEND = 0,
};

@interface ComGoogleCommonIoFileWriteModeEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComGoogleCommonIoFileWriteModeEnum_values();

+ (ComGoogleCommonIoFileWriteModeEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComGoogleCommonIoFileWriteModeEnum *ComGoogleCommonIoFileWriteModeEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonIoFileWriteModeEnum)

FOUNDATION_EXPORT ComGoogleCommonIoFileWriteModeEnum *ComGoogleCommonIoFileWriteModeEnum_values_[];

#define ComGoogleCommonIoFileWriteModeEnum_APPEND ComGoogleCommonIoFileWriteModeEnum_values_[ComGoogleCommonIoFileWriteMode_APPEND]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleCommonIoFileWriteModeEnum, APPEND)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoFileWriteModeEnum)

#endif

#pragma pop_macro("ComGoogleCommonIoFileWriteMode_INCLUDE_ALL")
