//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/internal/exceptions/VerificationAwareInvocation.java
//

#ifndef _OrgMockitoInternalExceptionsVerificationAwareInvocation_H_
#define _OrgMockitoInternalExceptionsVerificationAwareInvocation_H_

#include <j2objc/J2ObjC_header.h>
#include <j2objc/org/mockito/invocation/DescribedInvocation.h>

@protocol OrgMockitoInternalExceptionsVerificationAwareInvocation < OrgMockitoInvocationDescribedInvocation, NSObject, JavaObject >

- (jboolean)isVerified;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalExceptionsVerificationAwareInvocation)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalExceptionsVerificationAwareInvocation)

#endif // _OrgMockitoInternalExceptionsVerificationAwareInvocation_H_
