//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/internal/InOrderImpl.java
//

#ifndef _OrgMockitoInternalInOrderImpl_H_
#define _OrgMockitoInternalInOrderImpl_H_

#include "../../../J2ObjC_header.h"
#include "../../../org/mockito/InOrder.h"
#include "../../../org/mockito/internal/verification/api/InOrderContext.h"

@protocol JavaUtilList;
@protocol OrgMockitoInvocationInvocation;
@protocol OrgMockitoVerificationVerificationMode;

@interface OrgMockitoInternalInOrderImpl : NSObject < OrgMockitoInOrder, OrgMockitoInternalVerificationApiInOrderContext >

#pragma mark Public

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)mocksToBeVerifiedInOrder;

- (id<JavaUtilList>)getMocksToBeVerifiedInOrder;

- (jboolean)isVerifiedWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)i;

- (void)markVerifiedWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)i;

- (id)verifyWithId:(id)mock;

- (id)verifyWithId:(id)mock
withOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)mode;

- (void)verifyNoMoreInteractions;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalInOrderImpl)

FOUNDATION_EXPORT void OrgMockitoInternalInOrderImpl_initWithJavaUtilList_(OrgMockitoInternalInOrderImpl *self, id<JavaUtilList> mocksToBeVerifiedInOrder);

FOUNDATION_EXPORT OrgMockitoInternalInOrderImpl *new_OrgMockitoInternalInOrderImpl_initWithJavaUtilList_(id<JavaUtilList> mocksToBeVerifiedInOrder) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalInOrderImpl)

#endif // _OrgMockitoInternalInOrderImpl_H_
