//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/asn1/BerOutputStream.java
//

#ifndef _OrgApacheHarmonySecurityAsn1BerOutputStream_H_
#define _OrgApacheHarmonySecurityAsn1BerOutputStream_H_

#include "../../../../../J2ObjC_header.h"

@class IOSByteArray;
@class OrgApacheHarmonySecurityAsn1ASN1Choice;
@class OrgApacheHarmonySecurityAsn1ASN1Explicit;
@class OrgApacheHarmonySecurityAsn1ASN1Sequence;
@class OrgApacheHarmonySecurityAsn1ASN1SequenceOf;
@class OrgApacheHarmonySecurityAsn1ASN1Set;
@class OrgApacheHarmonySecurityAsn1ASN1SetOf;

/*!
 @author Vladimir N. Molotkov, Stepan M. Mishura
 @version $Revision$
 */

/*!
 @brief Encodes ASN.1 types with BER (X.690)
 */
@interface OrgApacheHarmonySecurityAsn1BerOutputStream : NSObject {
 @public
  /*!
   @brief Encoded byte array
   */
  IOSByteArray *encoded_;
  /*!
   @brief current offset
   */
  jint offset_;
  /*!
   @brief Current encoded length
   */
  jint length_;
  /*!
   @brief Current encoded content
   */
  id content_;
}

#pragma mark Public

- (instancetype)init;

- (void)encodeANY;

- (void)encodeBitString;

- (void)encodeBoolean;

- (void)encodeChoiceWithOrgApacheHarmonySecurityAsn1ASN1Choice:(OrgApacheHarmonySecurityAsn1ASN1Choice *)choice;

- (void)encodeExplicitWithOrgApacheHarmonySecurityAsn1ASN1Explicit:(OrgApacheHarmonySecurityAsn1ASN1Explicit *)explicit_;

- (void)encodeGeneralizedTime;

- (void)encodeInteger;

- (void)encodeOctetString;

- (void)encodeOID;

- (void)encodeSequenceWithOrgApacheHarmonySecurityAsn1ASN1Sequence:(OrgApacheHarmonySecurityAsn1ASN1Sequence *)sequence;

- (void)encodeSequenceOfWithOrgApacheHarmonySecurityAsn1ASN1SequenceOf:(OrgApacheHarmonySecurityAsn1ASN1SequenceOf *)sequenceOf;

- (void)encodeSetWithOrgApacheHarmonySecurityAsn1ASN1Set:(OrgApacheHarmonySecurityAsn1ASN1Set *)set;

- (void)encodeSetOfWithOrgApacheHarmonySecurityAsn1ASN1SetOf:(OrgApacheHarmonySecurityAsn1ASN1SetOf *)setOf;

- (void)encodeString;

- (void)encodeTagWithInt:(jint)tag;

- (void)encodeUTCTime;

- (void)getChoiceLengthWithOrgApacheHarmonySecurityAsn1ASN1Choice:(OrgApacheHarmonySecurityAsn1ASN1Choice *)choice;

- (void)getExplicitLengthWithOrgApacheHarmonySecurityAsn1ASN1Explicit:(OrgApacheHarmonySecurityAsn1ASN1Explicit *)sequence;

- (void)getSequenceLengthWithOrgApacheHarmonySecurityAsn1ASN1Sequence:(OrgApacheHarmonySecurityAsn1ASN1Sequence *)sequence;

- (void)getSequenceOfLengthWithOrgApacheHarmonySecurityAsn1ASN1SequenceOf:(OrgApacheHarmonySecurityAsn1ASN1SequenceOf *)sequence;

- (void)getSetLengthWithOrgApacheHarmonySecurityAsn1ASN1Set:(OrgApacheHarmonySecurityAsn1ASN1Set *)set;

- (void)getSetOfLengthWithOrgApacheHarmonySecurityAsn1ASN1SetOf:(OrgApacheHarmonySecurityAsn1ASN1SetOf *)setOf;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheHarmonySecurityAsn1BerOutputStream)

J2OBJC_FIELD_SETTER(OrgApacheHarmonySecurityAsn1BerOutputStream, encoded_, IOSByteArray *)
J2OBJC_FIELD_SETTER(OrgApacheHarmonySecurityAsn1BerOutputStream, content_, id)

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1BerOutputStream_init(OrgApacheHarmonySecurityAsn1BerOutputStream *self);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1BerOutputStream *new_OrgApacheHarmonySecurityAsn1BerOutputStream_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityAsn1BerOutputStream)

#endif // _OrgApacheHarmonySecurityAsn1BerOutputStream_H_
