//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/asn1/DerInputStream.java
//

#ifndef _OrgApacheHarmonySecurityAsn1DerInputStream_H_
#define _OrgApacheHarmonySecurityAsn1DerInputStream_H_

#include <j2objc/J2ObjC_header.h>
#include <j2objc/org/apache/harmony/security/asn1/BerInputStream.h>

@class IOSByteArray;
@class JavaIoInputStream;
@class OrgApacheHarmonySecurityAsn1ASN1Sequence;
@class OrgApacheHarmonySecurityAsn1ASN1SetOf;
@class OrgApacheHarmonySecurityAsn1ASN1StringType;

/*!
 @author Stepan M. Mishura
 @version $Revision$
 */

/*!
 @brief Decodes ASN.1 types encoded with DER (X.690)
 */
@interface OrgApacheHarmonySecurityAsn1DerInputStream : OrgApacheHarmonySecurityAsn1BerInputStream

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)encoded;

- (instancetype)initWithByteArray:(IOSByteArray *)encoded
                          withInt:(jint)offset
                          withInt:(jint)encodingLen;

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (jint)next;

- (void)readBitString;

- (void)readBoolean;

- (void)readGeneralizedTime;

- (void)readOctetString;

- (void)readSequenceWithOrgApacheHarmonySecurityAsn1ASN1Sequence:(OrgApacheHarmonySecurityAsn1ASN1Sequence *)sequence;

- (void)readSetOfWithOrgApacheHarmonySecurityAsn1ASN1SetOf:(OrgApacheHarmonySecurityAsn1ASN1SetOf *)setOf;

- (void)readStringWithOrgApacheHarmonySecurityAsn1ASN1StringType:(OrgApacheHarmonySecurityAsn1ASN1StringType *)type;

- (void)readUTCTime;

@end

J2OBJC_STATIC_INIT(OrgApacheHarmonySecurityAsn1DerInputStream)

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1DerInputStream_initWithByteArray_(OrgApacheHarmonySecurityAsn1DerInputStream *self, IOSByteArray *encoded);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1DerInputStream *new_OrgApacheHarmonySecurityAsn1DerInputStream_initWithByteArray_(IOSByteArray *encoded) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1DerInputStream_initWithByteArray_withInt_withInt_(OrgApacheHarmonySecurityAsn1DerInputStream *self, IOSByteArray *encoded, jint offset, jint encodingLen);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1DerInputStream *new_OrgApacheHarmonySecurityAsn1DerInputStream_initWithByteArray_withInt_withInt_(IOSByteArray *encoded, jint offset, jint encodingLen) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void OrgApacheHarmonySecurityAsn1DerInputStream_initWithJavaIoInputStream_(OrgApacheHarmonySecurityAsn1DerInputStream *self, JavaIoInputStream *inArg);

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1DerInputStream *new_OrgApacheHarmonySecurityAsn1DerInputStream_initWithJavaIoInputStream_(JavaIoInputStream *inArg) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityAsn1DerInputStream)

#endif // _OrgApacheHarmonySecurityAsn1DerInputStream_H_
