//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/cache/LongAddables.java
//

#include "../../../../../J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCacheLongAddables")
#ifdef RESTRICT_ComGoogleCommonCacheLongAddables
#define INCLUDE_ALL_ComGoogleCommonCacheLongAddables 0
#else
#define INCLUDE_ALL_ComGoogleCommonCacheLongAddables 1
#endif
#undef RESTRICT_ComGoogleCommonCacheLongAddables

#if !defined (ComGoogleCommonCacheLongAddables_) && (INCLUDE_ALL_ComGoogleCommonCacheLongAddables || defined(INCLUDE_ComGoogleCommonCacheLongAddables))
#define ComGoogleCommonCacheLongAddables_

@protocol ComGoogleCommonCacheLongAddable;

@interface ComGoogleCommonCacheLongAddables : NSObject

#pragma mark Public

+ (id<ComGoogleCommonCacheLongAddable>)create;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonCacheLongAddables)

FOUNDATION_EXPORT id<ComGoogleCommonCacheLongAddable> ComGoogleCommonCacheLongAddables_create();

FOUNDATION_EXPORT void ComGoogleCommonCacheLongAddables_init(ComGoogleCommonCacheLongAddables *self);

FOUNDATION_EXPORT ComGoogleCommonCacheLongAddables *new_ComGoogleCommonCacheLongAddables_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCacheLongAddables *create_ComGoogleCommonCacheLongAddables_init();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCacheLongAddables)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCacheLongAddables")
