//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/io/AsynchronousCloseMonitor.java
//

#ifndef _LibcoreIoAsynchronousCloseMonitor_H_
#define _LibcoreIoAsynchronousCloseMonitor_H_

#include <j2objc/J2ObjC_header.h>

@class JavaIoFileDescriptor;

@interface LibcoreIoAsynchronousCloseMonitor : NSObject

#pragma mark Public

+ (id)newAsynchronousSocketCloseMonitorWithInt:(jint)fd OBJC_METHOD_FAMILY_NONE;

+ (void)signalBlockedThreadsWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;

@end

J2OBJC_EMPTY_STATIC_INIT(LibcoreIoAsynchronousCloseMonitor)

FOUNDATION_EXPORT void LibcoreIoAsynchronousCloseMonitor_signalBlockedThreadsWithJavaIoFileDescriptor_(JavaIoFileDescriptor *fd);

FOUNDATION_EXPORT id LibcoreIoAsynchronousCloseMonitor_newAsynchronousSocketCloseMonitorWithInt_(jint fd);

J2OBJC_TYPE_LITERAL_HEADER(LibcoreIoAsynchronousCloseMonitor)

#endif // _LibcoreIoAsynchronousCloseMonitor_H_
