//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/javax/annotation/PostConstruct.java
//

#ifndef _JavaxAnnotationPostConstruct_H_
#define _JavaxAnnotationPostConstruct_H_

#include "../../J2ObjC_header.h"
#include "../../java/lang/annotation/Annotation.h"

/*!
 @brief javax.annotation.PostConstruct annotation.
 No code was referenced,
 created using just its public API.
 */
@protocol JavaxAnnotationPostConstruct < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationPostConstruct : NSObject < JavaxAnnotationPostConstruct >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxAnnotationPostConstruct)

J2OBJC_TYPE_LITERAL_HEADER(JavaxAnnotationPostConstruct)

#endif // _JavaxAnnotationPostConstruct_H_
