//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/annotation/Inherited.java
//

#include "../../../J2ObjC_header.h"

#pragma push_macro("JavaLangAnnotationInherited_INCLUDE_ALL")
#ifdef JavaLangAnnotationInherited_RESTRICT
#define JavaLangAnnotationInherited_INCLUDE_ALL 0
#else
#define JavaLangAnnotationInherited_INCLUDE_ALL 1
#endif
#undef JavaLangAnnotationInherited_RESTRICT

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (JavaLangAnnotationInherited_) && (JavaLangAnnotationInherited_INCLUDE_ALL || defined(JavaLangAnnotationInherited_INCLUDE))
#define JavaLangAnnotationInherited_

#define JavaLangAnnotationAnnotation_RESTRICT 1
#define JavaLangAnnotationAnnotation_INCLUDE 1
#include "../../../java/lang/annotation/Annotation.h"

/*!
 @brief Defines a meta-annotation for indicating that an annotation is automatically
 inherited.
 @since 1.5
 */
@protocol JavaLangAnnotationInherited < JavaLangAnnotationAnnotation >

@end

@interface JavaLangAnnotationInherited : NSObject < JavaLangAnnotationInherited >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangAnnotationInherited)

J2OBJC_TYPE_LITERAL_HEADER(JavaLangAnnotationInherited)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("JavaLangAnnotationInherited_INCLUDE_ALL")
