//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/collect/AbstractSortedKeySortedSetMultimap.java
//

#include "../../../../../J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap")
#ifdef RESTRICT_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap
#define INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap 1
#endif
#undef RESTRICT_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap

#if !defined (ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap_) && (INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap || defined(INCLUDE_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap))
#define ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap_

#define RESTRICT_ComGoogleCommonCollectAbstractSortedSetMultimap 1
#define INCLUDE_ComGoogleCommonCollectAbstractSortedSetMultimap 1
#include "../../../../../com/google/common/collect/AbstractSortedSetMultimap.h"

@protocol JavaUtilSortedMap;
@protocol JavaUtilSortedSet;

@interface ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap : ComGoogleCommonCollectAbstractSortedSetMultimap

#pragma mark Public

- (id<JavaUtilSortedMap>)asMap;

- (id<JavaUtilSortedSet>)keySet;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)map;

- (id<JavaUtilSortedMap>)backingMap;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap)

FOUNDATION_EXPORT void ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap_initWithJavaUtilSortedMap_(ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap *self, id<JavaUtilSortedMap> map);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap")
