//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/collect/Interner.java
//

#include "../../../../../J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectInterner")
#ifdef RESTRICT_ComGoogleCommonCollectInterner
#define INCLUDE_ALL_ComGoogleCommonCollectInterner 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectInterner 1
#endif
#undef RESTRICT_ComGoogleCommonCollectInterner

#if !defined (ComGoogleCommonCollectInterner_) && (INCLUDE_ALL_ComGoogleCommonCollectInterner || defined(INCLUDE_ComGoogleCommonCollectInterner))
#define ComGoogleCommonCollectInterner_

@protocol ComGoogleCommonCollectInterner < JavaObject >

- (id)internWithId:(id)sample;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectInterner)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectInterner)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectInterner")
