//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/junit/build_result/java/org/junit/internal/builders/AnnotatedBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder")
#ifdef RESTRICT_OrgJunitInternalBuildersAnnotatedBuilder
#define INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder 0
#else
#define INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder 1
#endif
#undef RESTRICT_OrgJunitInternalBuildersAnnotatedBuilder

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (OrgJunitInternalBuildersAnnotatedBuilder_) && (INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder || defined(INCLUDE_OrgJunitInternalBuildersAnnotatedBuilder))
#define OrgJunitInternalBuildersAnnotatedBuilder_

#define RESTRICT_OrgJunitRunnersModelRunnerBuilder 1
#define INCLUDE_OrgJunitRunnersModelRunnerBuilder 1
#include "org/junit/runners/model/RunnerBuilder.h"

@class IOSClass;
@class OrgJunitRunnerRunner;

@interface OrgJunitInternalBuildersAnnotatedBuilder : OrgJunitRunnersModelRunnerBuilder

#pragma mark Public

- (instancetype)initWithOrgJunitRunnersModelRunnerBuilder:(OrgJunitRunnersModelRunnerBuilder *)suiteBuilder;

- (OrgJunitRunnerRunner *)buildRunnerWithIOSClass:(IOSClass *)runnerClass
                                     withIOSClass:(IOSClass *)testClass;

- (OrgJunitRunnerRunner *)runnerForClassWithIOSClass:(IOSClass *)testClass;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalBuildersAnnotatedBuilder)

FOUNDATION_EXPORT void OrgJunitInternalBuildersAnnotatedBuilder_initWithOrgJunitRunnersModelRunnerBuilder_(OrgJunitInternalBuildersAnnotatedBuilder *self, OrgJunitRunnersModelRunnerBuilder *suiteBuilder);

FOUNDATION_EXPORT OrgJunitInternalBuildersAnnotatedBuilder *new_OrgJunitInternalBuildersAnnotatedBuilder_initWithOrgJunitRunnersModelRunnerBuilder_(OrgJunitRunnersModelRunnerBuilder *suiteBuilder) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalBuildersAnnotatedBuilder *create_OrgJunitInternalBuildersAnnotatedBuilder_initWithOrgJunitRunnersModelRunnerBuilder_(OrgJunitRunnersModelRunnerBuilder *suiteBuilder);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalBuildersAnnotatedBuilder)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalBuildersAnnotatedBuilder")
