//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/com/google/j2objc/security/IosRSAKeyPairGenerator.java
//

#ifndef _ComGoogleJ2objcSecurityIosRSAKeyPairGenerator_H_
#define _ComGoogleJ2objcSecurityIosRSAKeyPairGenerator_H_

#include "../../../../J2ObjC_header.h"
#include "../../../../java/security/KeyPairGeneratorSpi.h"

@class JavaSecurityKeyPair;
@class JavaSecuritySecureRandom;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

@interface ComGoogleJ2objcSecurityIosRSAKeyPairGenerator : JavaSecurityKeyPairGeneratorSpi

#pragma mark Public

- (instancetype)init;

- (JavaSecurityKeyPair *)generateKeyPair;

- (void)initialize__WithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)params
                                  withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

- (void)initialize__WithInt:(jint)keySize
withJavaSecuritySecureRandom:(JavaSecuritySecureRandom *)random OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleJ2objcSecurityIosRSAKeyPairGenerator)

FOUNDATION_EXPORT void ComGoogleJ2objcSecurityIosRSAKeyPairGenerator_init(ComGoogleJ2objcSecurityIosRSAKeyPairGenerator *self);

FOUNDATION_EXPORT ComGoogleJ2objcSecurityIosRSAKeyPairGenerator *new_ComGoogleJ2objcSecurityIosRSAKeyPairGenerator_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleJ2objcSecurityIosRSAKeyPairGenerator)

#endif // _ComGoogleJ2objcSecurityIosRSAKeyPairGenerator_H_
