//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/base/Predicate.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonBasePredicate")
#ifdef RESTRICT_ComGoogleCommonBasePredicate
#define INCLUDE_ALL_ComGoogleCommonBasePredicate 0
#else
#define INCLUDE_ALL_ComGoogleCommonBasePredicate 1
#endif
#undef RESTRICT_ComGoogleCommonBasePredicate

#if !defined (ComGoogleCommonBasePredicate_) && (INCLUDE_ALL_ComGoogleCommonBasePredicate || defined(INCLUDE_ComGoogleCommonBasePredicate))
#define ComGoogleCommonBasePredicate_

@protocol ComGoogleCommonBasePredicate < JavaObject >

- (jboolean)applyWithId:(id)input;

- (jboolean)isEqual:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBasePredicate)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBasePredicate)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonBasePredicate")
