//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/base/Suppliers.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonBaseSuppliers")
#ifdef RESTRICT_ComGoogleCommonBaseSuppliers
#define INCLUDE_ALL_ComGoogleCommonBaseSuppliers 0
#else
#define INCLUDE_ALL_ComGoogleCommonBaseSuppliers 1
#endif
#undef RESTRICT_ComGoogleCommonBaseSuppliers

#if !defined (ComGoogleCommonBaseSuppliers_) && (INCLUDE_ALL_ComGoogleCommonBaseSuppliers || defined(INCLUDE_ComGoogleCommonBaseSuppliers))
#define ComGoogleCommonBaseSuppliers_

@class JavaUtilConcurrentTimeUnit;
@protocol ComGoogleCommonBaseFunction;
@protocol ComGoogleCommonBaseSupplier;

@interface ComGoogleCommonBaseSuppliers : NSObject

#pragma mark Public

+ (id<ComGoogleCommonBaseSupplier>)composeWithComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function
                                          withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)supplier;

+ (id<ComGoogleCommonBaseSupplier>)memoizeWithComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)delegate;

+ (id<ComGoogleCommonBaseSupplier>)memoizeWithExpirationWithComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)delegate
                                                                               withLong:(jlong)duration
                                                         withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

+ (id<ComGoogleCommonBaseSupplier>)ofInstanceWithId:(id)instance;

+ (id<ComGoogleCommonBaseFunction>)supplierFunction;

+ (id<ComGoogleCommonBaseSupplier>)synchronizedSupplierWithComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)delegate;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBaseSuppliers)

FOUNDATION_EXPORT id<ComGoogleCommonBaseSupplier> ComGoogleCommonBaseSuppliers_composeWithComGoogleCommonBaseFunction_withComGoogleCommonBaseSupplier_(id<ComGoogleCommonBaseFunction> function, id<ComGoogleCommonBaseSupplier> supplier);

FOUNDATION_EXPORT id<ComGoogleCommonBaseSupplier> ComGoogleCommonBaseSuppliers_memoizeWithComGoogleCommonBaseSupplier_(id<ComGoogleCommonBaseSupplier> delegate);

FOUNDATION_EXPORT id<ComGoogleCommonBaseSupplier> ComGoogleCommonBaseSuppliers_memoizeWithExpirationWithComGoogleCommonBaseSupplier_withLong_withJavaUtilConcurrentTimeUnit_(id<ComGoogleCommonBaseSupplier> delegate, jlong duration, JavaUtilConcurrentTimeUnit *unit);

FOUNDATION_EXPORT id<ComGoogleCommonBaseSupplier> ComGoogleCommonBaseSuppliers_ofInstanceWithId_(id instance);

FOUNDATION_EXPORT id<ComGoogleCommonBaseSupplier> ComGoogleCommonBaseSuppliers_synchronizedSupplierWithComGoogleCommonBaseSupplier_(id<ComGoogleCommonBaseSupplier> delegate);

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonBaseSuppliers_supplierFunction();

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBaseSuppliers)

#endif

#if !defined (ComGoogleCommonBaseSuppliers_MemoizingSupplier_) && (INCLUDE_ALL_ComGoogleCommonBaseSuppliers || defined(INCLUDE_ComGoogleCommonBaseSuppliers_MemoizingSupplier))
#define ComGoogleCommonBaseSuppliers_MemoizingSupplier_

#define RESTRICT_ComGoogleCommonBaseSupplier 1
#define INCLUDE_ComGoogleCommonBaseSupplier 1
#include "com/google/common/base/Supplier.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@interface ComGoogleCommonBaseSuppliers_MemoizingSupplier : NSObject < ComGoogleCommonBaseSupplier, JavaIoSerializable > {
 @public
  id<ComGoogleCommonBaseSupplier> delegate_;
  volatile_jboolean initialized_;
  id value_;
}

#pragma mark Public

- (id)get;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)delegate;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBaseSuppliers_MemoizingSupplier)

J2OBJC_FIELD_SETTER(ComGoogleCommonBaseSuppliers_MemoizingSupplier, delegate_, id<ComGoogleCommonBaseSupplier>)
J2OBJC_FIELD_SETTER(ComGoogleCommonBaseSuppliers_MemoizingSupplier, value_, id)

FOUNDATION_EXPORT void ComGoogleCommonBaseSuppliers_MemoizingSupplier_initWithComGoogleCommonBaseSupplier_(ComGoogleCommonBaseSuppliers_MemoizingSupplier *self, id<ComGoogleCommonBaseSupplier> delegate);

FOUNDATION_EXPORT ComGoogleCommonBaseSuppliers_MemoizingSupplier *new_ComGoogleCommonBaseSuppliers_MemoizingSupplier_initWithComGoogleCommonBaseSupplier_(id<ComGoogleCommonBaseSupplier> delegate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonBaseSuppliers_MemoizingSupplier *create_ComGoogleCommonBaseSuppliers_MemoizingSupplier_initWithComGoogleCommonBaseSupplier_(id<ComGoogleCommonBaseSupplier> delegate);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBaseSuppliers_MemoizingSupplier)

#endif

#if !defined (ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier_) && (INCLUDE_ALL_ComGoogleCommonBaseSuppliers || defined(INCLUDE_ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier))
#define ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier_

#define RESTRICT_ComGoogleCommonBaseSupplier 1
#define INCLUDE_ComGoogleCommonBaseSupplier 1
#include "com/google/common/base/Supplier.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaUtilConcurrentTimeUnit;

@interface ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier : NSObject < ComGoogleCommonBaseSupplier, JavaIoSerializable > {
 @public
  id<ComGoogleCommonBaseSupplier> delegate_;
  jlong durationNanos_;
  volatile_id value_;
  volatile_jlong expirationNanos_;
}

#pragma mark Public

- (id)get;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)delegate
                                           withLong:(jlong)duration
                     withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier)

J2OBJC_FIELD_SETTER(ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier, delegate_, id<ComGoogleCommonBaseSupplier>)
J2OBJC_VOLATILE_FIELD_SETTER(ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier, value_, id)

FOUNDATION_EXPORT void ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier_initWithComGoogleCommonBaseSupplier_withLong_withJavaUtilConcurrentTimeUnit_(ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier *self, id<ComGoogleCommonBaseSupplier> delegate, jlong duration, JavaUtilConcurrentTimeUnit *unit);

FOUNDATION_EXPORT ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier *new_ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier_initWithComGoogleCommonBaseSupplier_withLong_withJavaUtilConcurrentTimeUnit_(id<ComGoogleCommonBaseSupplier> delegate, jlong duration, JavaUtilConcurrentTimeUnit *unit) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier *create_ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier_initWithComGoogleCommonBaseSupplier_withLong_withJavaUtilConcurrentTimeUnit_(id<ComGoogleCommonBaseSupplier> delegate, jlong duration, JavaUtilConcurrentTimeUnit *unit);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBaseSuppliers_ExpiringMemoizingSupplier)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonBaseSuppliers")
