//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/junit/build_result/java/org/junit/internal/runners/ErrorReportingRunner.java
//

#ifndef _OrgJunitInternalRunnersErrorReportingRunner_H_
#define _OrgJunitInternalRunnersErrorReportingRunner_H_

#include <j2objc/J2ObjC_header.h>
#include <j2objc/org/junit/runner/Runner.h>

@class IOSClass;
@class JavaLangThrowable;
@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationRunNotifier;

@interface OrgJunitInternalRunnersErrorReportingRunner : OrgJunitRunnerRunner

#pragma mark Public

- (instancetype)initWithIOSClass:(IOSClass *)testClass
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (OrgJunitRunnerDescription *)getDescription;

- (void)runWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalRunnersErrorReportingRunner)

FOUNDATION_EXPORT void OrgJunitInternalRunnersErrorReportingRunner_initWithIOSClass_withJavaLangThrowable_(OrgJunitInternalRunnersErrorReportingRunner *self, IOSClass *testClass, JavaLangThrowable *cause);

FOUNDATION_EXPORT OrgJunitInternalRunnersErrorReportingRunner *new_OrgJunitInternalRunnersErrorReportingRunner_initWithIOSClass_withJavaLangThrowable_(IOSClass *testClass, JavaLangThrowable *cause) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalRunnersErrorReportingRunner)

#endif // _OrgJunitInternalRunnersErrorReportingRunner_H_
