//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/guava/sources/com/google/common/collect/ForwardingMultiset.java
//

#include <j2objc/J2ObjC_header.h>

#pragma push_macro("ComGoogleCommonCollectForwardingMultiset_INCLUDE_ALL")
#if ComGoogleCommonCollectForwardingMultiset_RESTRICT
#define ComGoogleCommonCollectForwardingMultiset_INCLUDE_ALL 0
#else
#define ComGoogleCommonCollectForwardingMultiset_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectForwardingMultiset_RESTRICT

#if !defined (_ComGoogleCommonCollectForwardingMultiset_) && (ComGoogleCommonCollectForwardingMultiset_INCLUDE_ALL || ComGoogleCommonCollectForwardingMultiset_INCLUDE)
#define _ComGoogleCommonCollectForwardingMultiset_

#define ComGoogleCommonCollectForwardingCollection_RESTRICT 1
#define ComGoogleCommonCollectForwardingCollection_INCLUDE 1
#include <j2objc/com/google/common/collect/ForwardingCollection.h>

#define ComGoogleCommonCollectMultiset_RESTRICT 1
#define ComGoogleCommonCollectMultiset_INCLUDE 1
#include <j2objc/com/google/common/collect/Multiset.h>

@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectForwardingMultiset : ComGoogleCommonCollectForwardingCollection < ComGoogleCommonCollectMultiset >

#pragma mark Public

- (jint)addWithId:(id)element
          withInt:(jint)occurrences;

- (jint)countWithId:(id)element;

- (id<JavaUtilSet>)elementSet;

- (id<JavaUtilSet>)entrySet;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (jint)removeWithId:(id)element
             withInt:(jint)occurrences;

- (jint)setCountWithId:(id)element
               withInt:(jint)count;

- (jboolean)setCountWithId:(id)element
                   withInt:(jint)oldCount
                   withInt:(jint)newCount;

#pragma mark Protected

- (instancetype)init;

- (id<ComGoogleCommonCollectMultiset>)delegate;

- (jboolean)standardAddWithId:(id)element;

- (jboolean)standardAddAllWithJavaUtilCollection:(id<JavaUtilCollection>)elementsToAdd;

- (void)standardClear;

- (jboolean)standardContainsWithId:(id)object;

- (jint)standardCountWithId:(id)object;

- (jboolean)standardEqualsWithId:(id)object;

- (jint)standardHashCode;

- (id<JavaUtilIterator>)standardIterator;

- (jboolean)standardRemoveWithId:(id)element;

- (jboolean)standardRemoveAllWithJavaUtilCollection:(id<JavaUtilCollection>)elementsToRemove;

- (jboolean)standardRetainAllWithJavaUtilCollection:(id<JavaUtilCollection>)elementsToRetain;

- (jint)standardSetCountWithId:(id)element
                       withInt:(jint)count;

- (jboolean)standardSetCountWithId:(id)element
                           withInt:(jint)oldCount
                           withInt:(jint)newCount;

- (jint)standardSize;

- (NSString *)standardToString;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectForwardingMultiset)

FOUNDATION_EXPORT void ComGoogleCommonCollectForwardingMultiset_init(ComGoogleCommonCollectForwardingMultiset *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectForwardingMultiset)

#endif

#if !defined (_ComGoogleCommonCollectForwardingMultiset_StandardElementSet_) && (ComGoogleCommonCollectForwardingMultiset_INCLUDE_ALL || ComGoogleCommonCollectForwardingMultiset_StandardElementSet_INCLUDE)
#define _ComGoogleCommonCollectForwardingMultiset_StandardElementSet_

#define ComGoogleCommonCollectMultisets_RESTRICT 1
#define ComGoogleCommonCollectMultisets_ElementSet_INCLUDE 1
#include <j2objc/com/google/common/collect/Multisets.h>

@class ComGoogleCommonCollectForwardingMultiset;
@protocol ComGoogleCommonCollectMultiset;

@interface ComGoogleCommonCollectForwardingMultiset_StandardElementSet : ComGoogleCommonCollectMultisets_ElementSet

#pragma mark Public

- (instancetype)initWithComGoogleCommonCollectForwardingMultiset:(ComGoogleCommonCollectForwardingMultiset *)outer$;

#pragma mark Package-Private

- (id<ComGoogleCommonCollectMultiset>)multiset;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectForwardingMultiset_StandardElementSet)

FOUNDATION_EXPORT void ComGoogleCommonCollectForwardingMultiset_StandardElementSet_initWithComGoogleCommonCollectForwardingMultiset_(ComGoogleCommonCollectForwardingMultiset_StandardElementSet *self, ComGoogleCommonCollectForwardingMultiset *outer$);

FOUNDATION_EXPORT ComGoogleCommonCollectForwardingMultiset_StandardElementSet *new_ComGoogleCommonCollectForwardingMultiset_StandardElementSet_initWithComGoogleCommonCollectForwardingMultiset_(ComGoogleCommonCollectForwardingMultiset *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectForwardingMultiset_StandardElementSet)

#endif

#pragma pop_macro("ComGoogleCommonCollectForwardingMultiset_INCLUDE_ALL")
