//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/guava/sources/com/google/common/collect/ImmutableMapEntrySet.java
//

#include <j2objc/J2ObjC_header.h>

#pragma push_macro("ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL")
#if ComGoogleCommonCollectImmutableMapEntrySet_RESTRICT
#define ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL 0
#else
#define ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectImmutableMapEntrySet_RESTRICT

#if !defined (_ComGoogleCommonCollectImmutableMapEntrySet_) && (ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL || ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE)
#define _ComGoogleCommonCollectImmutableMapEntrySet_

#define ComGoogleCommonCollectImmutableSet_RESTRICT 1
#define ComGoogleCommonCollectImmutableSet_INCLUDE 1
#include <j2objc/com/google/common/collect/ImmutableSet.h>

@class ComGoogleCommonCollectImmutableMap;

@interface ComGoogleCommonCollectImmutableMapEntrySet : ComGoogleCommonCollectImmutableSet

#pragma mark Public

- (jboolean)containsWithId:(id)object;

- (jint)size;

#pragma mark Package-Private

- (instancetype)init;

- (jboolean)isPartialView;

- (ComGoogleCommonCollectImmutableMap *)map;

- (id)writeReplace;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectImmutableMapEntrySet)

FOUNDATION_EXPORT void ComGoogleCommonCollectImmutableMapEntrySet_init(ComGoogleCommonCollectImmutableMapEntrySet *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectImmutableMapEntrySet)

#endif

#pragma pop_macro("ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL")
