//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/SocketAddress.java
//

#include "../../J2ObjC_header.h"

#pragma push_macro("JavaNetSocketAddress_INCLUDE_ALL")
#ifdef JavaNetSocketAddress_RESTRICT
#define JavaNetSocketAddress_INCLUDE_ALL 0
#else
#define JavaNetSocketAddress_INCLUDE_ALL 1
#endif
#undef JavaNetSocketAddress_RESTRICT

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (JavaNetSocketAddress_) && (JavaNetSocketAddress_INCLUDE_ALL || defined(JavaNetSocketAddress_INCLUDE))
#define JavaNetSocketAddress_

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "../../java/io/Serializable.h"

/*!
 @brief This abstract class represents a protocol-independent base for
 socket-endpoint representing classes.
 The class has to be implemented
 according to a specific protocol.
 */
@interface JavaNetSocketAddress : NSObject < JavaIoSerializable >

#pragma mark Public

/*!
 @brief Creates a new <code>SocketAddress</code> instance.
 */
- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNetSocketAddress)

FOUNDATION_EXPORT void JavaNetSocketAddress_init(JavaNetSocketAddress *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaNetSocketAddress)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("JavaNetSocketAddress_INCLUDE_ALL")
