//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/regex/MatchResultImpl.java
//

#ifndef _JavaUtilRegexMatchResultImpl_H_
#define _JavaUtilRegexMatchResultImpl_H_

#include <j2objc/J2ObjC_header.h>
#include <j2objc/java/util/regex/MatchResult.h>

@class IOSIntArray;

/*!
 @brief Holds the results of a successful match of a regular expression against a
 given string.
 Only used internally, thus sparsely documented (though the
 defining public interface has full documentation).
 */
@interface JavaUtilRegexMatchResultImpl : NSObject < JavaUtilRegexMatchResult >

#pragma mark Public

- (jint)end;

- (jint)endWithInt:(jint)group;

- (NSString *)group;

- (NSString *)groupWithInt:(jint)group;

- (jint)groupCount;

- (jint)start;

- (jint)startWithInt:(jint)group;

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)text
                    withIntArray:(IOSIntArray *)offsets;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilRegexMatchResultImpl)

FOUNDATION_EXPORT void JavaUtilRegexMatchResultImpl_initWithNSString_withIntArray_(JavaUtilRegexMatchResultImpl *self, NSString *text, IOSIntArray *offsets);

FOUNDATION_EXPORT JavaUtilRegexMatchResultImpl *new_JavaUtilRegexMatchResultImpl_initWithNSString_withIntArray_(NSString *text, IOSIntArray *offsets) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilRegexMatchResultImpl)

#endif // _JavaUtilRegexMatchResultImpl_H_
