//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/pkcs7/SignerInfo.java
//

#ifndef _OrgApacheHarmonySecurityPkcs7SignerInfo_H_
#define _OrgApacheHarmonySecurityPkcs7SignerInfo_H_

#include <j2objc/J2ObjC_header.h>

@class IOSByteArray;
@class JavaMathBigInteger;
@class JavaxSecurityAuthX500X500Principal;
@class OrgApacheHarmonySecurityAsn1ASN1Sequence;
@protocol JavaUtilList;

/*!
 @author Boris Kuznetsov
 @version $Revision$
 */

/*!
 @brief As defined in PKCS #7: Cryptographic Message Syntax Standard
 (http://www.ietf.org/rfc/rfc2315.txt)
 SignerInfo ::= SEQUENCE {
 version Version,
 issuerAndSerialNumber IssuerAndSerialNumber,
 digestAlgorithm DigestAlgorithmIdentifier,
 authenticatedAttributes
 [0] IMPLICIT Attributes OPTIONAL,
 digestEncryptionAlgorithm
 DigestEncryptionAlgorithmIdentifier,
 encryptedDigest EncryptedDigest,
 unauthenticatedAttributes
 [1] IMPLICIT Attributes OPTIONAL
 }
 */
@interface OrgApacheHarmonySecurityPkcs7SignerInfo : NSObject

#pragma mark Public

- (id<JavaUtilList>)getAuthenticatedAttributes;

- (NSString *)getDigestAlgorithm;

- (NSString *)getDigestAlgorithmName;

- (NSString *)getDigestEncryptionAlgorithm;

- (NSString *)getDigestEncryptionAlgorithmName;

/*!
 @brief Returns the non-IMPLICIT ASN.1 encoding of the "authAttrs" from this
 SignerInfo.
 That is, it will return as the encoding of a generic ASN.1
 SET.
 */
- (IOSByteArray *)getEncodedAuthenticatedAttributes;

- (IOSByteArray *)getEncryptedDigest;

- (JavaxSecurityAuthX500X500Principal *)getIssuer;

- (JavaMathBigInteger *)getSerialNumber;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(OrgApacheHarmonySecurityPkcs7SignerInfo)

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1ASN1Sequence *OrgApacheHarmonySecurityPkcs7SignerInfo_ISSUER_AND_SERIAL_NUMBER_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonySecurityPkcs7SignerInfo, ISSUER_AND_SERIAL_NUMBER_, OrgApacheHarmonySecurityAsn1ASN1Sequence *)

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1ASN1Sequence *OrgApacheHarmonySecurityPkcs7SignerInfo_ASN1_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonySecurityPkcs7SignerInfo, ASN1_, OrgApacheHarmonySecurityAsn1ASN1Sequence *)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityPkcs7SignerInfo)

#endif // _OrgApacheHarmonySecurityPkcs7SignerInfo_H_
