//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/xml/xpath/XPathExpressionException.java
//

#include "../../../J2ObjC_header.h"

#pragma push_macro("JavaxXmlXpathXPathExpressionException_INCLUDE_ALL")
#ifdef JavaxXmlXpathXPathExpressionException_RESTRICT
#define JavaxXmlXpathXPathExpressionException_INCLUDE_ALL 0
#else
#define JavaxXmlXpathXPathExpressionException_INCLUDE_ALL 1
#endif
#undef JavaxXmlXpathXPathExpressionException_RESTRICT

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (JavaxXmlXpathXPathExpressionException_) && (JavaxXmlXpathXPathExpressionException_INCLUDE_ALL || defined(JavaxXmlXpathXPathExpressionException_INCLUDE))
#define JavaxXmlXpathXPathExpressionException_

#define JavaxXmlXpathXPathException_RESTRICT 1
#define JavaxXmlXpathXPathException_INCLUDE 1
#include "../../../javax/xml/xpath/XPathException.h"

@class JavaLangThrowable;

/*!
 @brief <code>XPathExpressionException</code> represents an error in an XPath expression.
 </p>
 @author <a href="mailto:Norman.Walsh@@Sun.com">Norman Walsh</a>
 @author <a href="mailto:Jeff.Suttor@@Sun.com">Jeff Suttor</a>
 @version $Revision: 446598 $, $Date: 2006-09-15 05:55:40 -0700 (Fri, 15 Sep 2006) $
 @since 1.5
 */
@interface JavaxXmlXpathXPathExpressionException : JavaxXmlXpathXPathException

#pragma mark Public

/*!
 @brief <p>Constructs a new <code>XPathExpressionException</code> with the specified detail <code>message</code>.
 </p>
 <p>The <code>cause</code> is not initialized.</p>
 <p>If <code>message</code> is <code>null</code>, then a <code>NullPointerException</code> is thrown.</p>
 @param message The detail message.
 */
- (instancetype)initWithNSString:(NSString *)message;

/*!
 @brief <p>Constructs a new <code>XPathExpressionException</code> with the specified <code>cause</code>.
 </p>
 <p>If <code>cause</code> is <code>null</code>, then a <code>NullPointerException</code> is thrown.</p>
 @param cause The cause.
 @throws NullPointerException if <code>cause</code> is <code>null</code>.
 */
- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxXmlXpathXPathExpressionException)

FOUNDATION_EXPORT void JavaxXmlXpathXPathExpressionException_initWithNSString_(JavaxXmlXpathXPathExpressionException *self, NSString *message);

FOUNDATION_EXPORT JavaxXmlXpathXPathExpressionException *new_JavaxXmlXpathXPathExpressionException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxXmlXpathXPathExpressionException_initWithJavaLangThrowable_(JavaxXmlXpathXPathExpressionException *self, JavaLangThrowable *cause);

FOUNDATION_EXPORT JavaxXmlXpathXPathExpressionException *new_JavaxXmlXpathXPathExpressionException_initWithJavaLangThrowable_(JavaLangThrowable *cause) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxXmlXpathXPathExpressionException)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("JavaxXmlXpathXPathExpressionException_INCLUDE_ALL")
