//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/LongArrayBuffer.java
//

#ifndef _JavaNioLongArrayBuffer_H_
#define _JavaNioLongArrayBuffer_H_

#include "../../J2ObjC_header.h"
#include "../../java/nio/LongBuffer.h"

@class IOSLongArray;
@class JavaNioByteOrder;

/*!
 @brief LongArrayBuffer implements long[]-based LongBuffers.
 */
@interface JavaNioLongArrayBuffer : JavaNioLongBuffer

#pragma mark Public

- (JavaNioLongBuffer *)asReadOnlyBuffer;

- (JavaNioLongBuffer *)compact;

- (JavaNioLongBuffer *)duplicate;

- (jlong)get;

- (jlong)getWithInt:(jint)index;

- (JavaNioLongBuffer *)getWithLongArray:(IOSLongArray *)dst
                                withInt:(jint)dstOffset
                                withInt:(jint)longCount;

- (jboolean)isDirect;

- (jboolean)isReadOnly;

- (JavaNioByteOrder *)order;

- (JavaNioLongBuffer *)putWithInt:(jint)index
                         withLong:(jlong)c;

- (JavaNioLongBuffer *)putWithLong:(jlong)c;

- (JavaNioLongBuffer *)putWithLongArray:(IOSLongArray *)src
                                withInt:(jint)srcOffset
                                withInt:(jint)longCount;

- (JavaNioLongBuffer *)slice;

#pragma mark Package-Private

- (instancetype)initWithLongArray:(IOSLongArray *)array;

- (IOSLongArray *)protectedArray;

- (jint)protectedArrayOffset;

- (jboolean)protectedHasArray;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioLongArrayBuffer)

FOUNDATION_EXPORT void JavaNioLongArrayBuffer_initWithLongArray_(JavaNioLongArrayBuffer *self, IOSLongArray *array);

FOUNDATION_EXPORT JavaNioLongArrayBuffer *new_JavaNioLongArrayBuffer_initWithLongArray_(IOSLongArray *array) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNioLongArrayBuffer)

#endif // _JavaNioLongArrayBuffer_H_
