//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/SelectorProviderImpl.java
//

#ifndef _JavaNioSelectorProviderImpl_H_
#define _JavaNioSelectorProviderImpl_H_

#include <j2objc/J2ObjC_header.h>
#include <j2objc/java/nio/channels/spi/SelectorProvider.h>

@class JavaNioChannelsDatagramChannel;
@class JavaNioChannelsPipe;
@class JavaNioChannelsServerSocketChannel;
@class JavaNioChannelsSocketChannel;
@class JavaNioChannelsSpiAbstractSelector;

/*!
  for java.nio.channels.spi.SelectorProvider only.
 */
@interface JavaNioSelectorProviderImpl : JavaNioChannelsSpiSelectorProvider

#pragma mark Public

- (instancetype)init;

- (JavaNioChannelsDatagramChannel *)openDatagramChannel;

- (JavaNioChannelsPipe *)openPipe;

- (JavaNioChannelsSpiAbstractSelector *)openSelector;

- (JavaNioChannelsServerSocketChannel *)openServerSocketChannel;

- (JavaNioChannelsSocketChannel *)openSocketChannel;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioSelectorProviderImpl)

FOUNDATION_EXPORT void JavaNioSelectorProviderImpl_init(JavaNioSelectorProviderImpl *self);

FOUNDATION_EXPORT JavaNioSelectorProviderImpl *new_JavaNioSelectorProviderImpl_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaNioSelectorProviderImpl)

#endif // _JavaNioSelectorProviderImpl_H_
