//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/reflect/GenericArrayType.java
//

#include "../../../J2ObjC_header.h"

#pragma push_macro("JavaLangReflectGenericArrayType_INCLUDE_ALL")
#ifdef JavaLangReflectGenericArrayType_RESTRICT
#define JavaLangReflectGenericArrayType_INCLUDE_ALL 0
#else
#define JavaLangReflectGenericArrayType_INCLUDE_ALL 1
#endif
#undef JavaLangReflectGenericArrayType_RESTRICT

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (JavaLangReflectGenericArrayType_) && (JavaLangReflectGenericArrayType_INCLUDE_ALL || defined(JavaLangReflectGenericArrayType_INCLUDE))
#define JavaLangReflectGenericArrayType_

#define JavaLangReflectType_RESTRICT 1
#define JavaLangReflectType_INCLUDE 1
#include "../../../java/lang/reflect/Type.h"

/*!
 @brief This interface represents an array type with a component type that is either
 a parameterized type or a type variable.
 @since 1.5
 */
@protocol JavaLangReflectGenericArrayType < JavaLangReflectType, NSObject, JavaObject >

/*!
 @brief Returns the component type of this array.
 @return the component type of this array
 @throws TypeNotPresentException
 if the component type points to a missing type
 @throws MalformedParameterizedTypeException
 if the component type points to a type that cannot be
 instantiated for some reason
 */
- (id<JavaLangReflectType>)getGenericComponentType;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangReflectGenericArrayType)

J2OBJC_TYPE_LITERAL_HEADER(JavaLangReflectGenericArrayType)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("JavaLangReflectGenericArrayType_INCLUDE_ALL")
