//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/logging/ConsoleHandler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaUtilLoggingConsoleHandler")
#ifdef RESTRICT_JavaUtilLoggingConsoleHandler
#define INCLUDE_ALL_JavaUtilLoggingConsoleHandler 0
#else
#define INCLUDE_ALL_JavaUtilLoggingConsoleHandler 1
#endif
#undef RESTRICT_JavaUtilLoggingConsoleHandler

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (JavaUtilLoggingConsoleHandler_) && (INCLUDE_ALL_JavaUtilLoggingConsoleHandler || defined(INCLUDE_JavaUtilLoggingConsoleHandler))
#define JavaUtilLoggingConsoleHandler_

#define RESTRICT_JavaUtilLoggingStreamHandler 1
#define INCLUDE_JavaUtilLoggingStreamHandler 1
#include "java/util/logging/StreamHandler.h"

@class JavaUtilLoggingLogRecord;

/*!
 @brief A handler that writes log messages to the standard output stream
 <code>System.err</code>.
 <p>
 This handler reads the following properties from the log manager to
 initialize itself:
 <ul>
 <li>java.util.logging.ConsoleHandler.level specifies the logging level,
 defaults to <code>Level.INFO</code> if this property is not found or has an
 invalid value.
 <li>java.util.logging.ConsoleHandler.filter specifies the name of the filter
 class to be associated with this handler, defaults to <code>null</code> if this
 property is not found or has an invalid value.
 <li>java.util.logging.ConsoleHandler.formatter specifies the name of the
 formatter class to be associated with this handler, defaults to
 <code>java.util.logging.SimpleFormatter</code> if this property is not found or
 has an invalid value.
 <li>java.util.logging.ConsoleHandler.encoding specifies the encoding this
 handler will use to encode log messages, defaults to <code>null</code> if this
 property is not found or has an invalid value.
 </ul>
 <p>
 This class is not thread-safe.
 */
@interface JavaUtilLoggingConsoleHandler : JavaUtilLoggingStreamHandler

#pragma mark Public

/*!
 @brief Constructs a <code>ConsoleHandler</code> object.
 */
- (instancetype)init;

/*!
 @brief Closes this handler.
 The <code>System.err</code> is flushed but not closed.
 */
- (void)close;

/*!
 @brief Logs a record if necessary.
 A flush operation will be done.
 @param record
 the log record to be logged.
 */
- (void)publishWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilLoggingConsoleHandler)

FOUNDATION_EXPORT void JavaUtilLoggingConsoleHandler_init(JavaUtilLoggingConsoleHandler *self);

FOUNDATION_EXPORT JavaUtilLoggingConsoleHandler *new_JavaUtilLoggingConsoleHandler_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaUtilLoggingConsoleHandler *create_JavaUtilLoggingConsoleHandler_init();

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilLoggingConsoleHandler)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_JavaUtilLoggingConsoleHandler")
