//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/src/j2objc/testing/mockito/build_result/java/org/mockito/internal/debugging/MockitoDebuggerImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalDebuggingMockitoDebuggerImpl")
#ifdef RESTRICT_OrgMockitoInternalDebuggingMockitoDebuggerImpl
#define INCLUDE_ALL_OrgMockitoInternalDebuggingMockitoDebuggerImpl 0
#else
#define INCLUDE_ALL_OrgMockitoInternalDebuggingMockitoDebuggerImpl 1
#endif
#undef RESTRICT_OrgMockitoInternalDebuggingMockitoDebuggerImpl

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (OrgMockitoInternalDebuggingMockitoDebuggerImpl_) && (INCLUDE_ALL_OrgMockitoInternalDebuggingMockitoDebuggerImpl || defined(INCLUDE_OrgMockitoInternalDebuggingMockitoDebuggerImpl))
#define OrgMockitoInternalDebuggingMockitoDebuggerImpl_

#define RESTRICT_OrgMockitoMockitoDebugger 1
#define INCLUDE_OrgMockitoMockitoDebugger 1
#include "org/mockito/MockitoDebugger.h"

@class IOSObjectArray;

@interface OrgMockitoInternalDebuggingMockitoDebuggerImpl : NSObject < OrgMockitoMockitoDebugger >

#pragma mark Public

- (instancetype)init;

- (NSString *)printInvocationsWithNSObjectArray:(IOSObjectArray *)mocks;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalDebuggingMockitoDebuggerImpl)

FOUNDATION_EXPORT void OrgMockitoInternalDebuggingMockitoDebuggerImpl_init(OrgMockitoInternalDebuggingMockitoDebuggerImpl *self);

FOUNDATION_EXPORT OrgMockitoInternalDebuggingMockitoDebuggerImpl *new_OrgMockitoInternalDebuggingMockitoDebuggerImpl_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalDebuggingMockitoDebuggerImpl *create_OrgMockitoInternalDebuggingMockitoDebuggerImpl_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalDebuggingMockitoDebuggerImpl)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalDebuggingMockitoDebuggerImpl")
