//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/collect/Maps.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectMaps")
#ifdef RESTRICT_ComGoogleCommonCollectMaps
#define INCLUDE_ALL_ComGoogleCommonCollectMaps 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectMaps 1
#endif
#undef RESTRICT_ComGoogleCommonCollectMaps
#ifdef INCLUDE_ComGoogleCommonCollectMaps_FilteredEntryBiMap
#define INCLUDE_ComGoogleCommonCollectMaps_FilteredEntryMap 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_NavigableKeySet
#define INCLUDE_ComGoogleCommonCollectMaps_SortedKeySet 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_SortedKeySet
#define INCLUDE_ComGoogleCommonCollectMaps_KeySet 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet
#define INCLUDE_ComGoogleCommonCollectMaps_KeySet 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_FilteredEntryMap
#define INCLUDE_ComGoogleCommonCollectMaps_AbstractFilteredMap 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_AbstractFilteredMap
#define INCLUDE_ComGoogleCommonCollectMaps_ViewCachingAbstractMap 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_TransformedEntriesSortedMap
#define INCLUDE_ComGoogleCommonCollectMaps_TransformedEntriesMap 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_TransformedEntriesMap
#define INCLUDE_ComGoogleCommonCollectMaps_IteratorBasedAbstractMap 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_UnmodifiableEntrySet
#define INCLUDE_ComGoogleCommonCollectMaps_UnmodifiableEntries 1
#endif
#ifdef INCLUDE_ComGoogleCommonCollectMaps_SortedMapDifferenceImpl
#define INCLUDE_ComGoogleCommonCollectMaps_MapDifferenceImpl 1
#endif

#if !defined (ComGoogleCommonCollectMaps_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps))
#define ComGoogleCommonCollectMaps_

@class ComGoogleCommonBaseConverter;
@class ComGoogleCommonBaseEquivalence;
@class ComGoogleCommonBaseJoiner_MapJoiner;
@class ComGoogleCommonCollectImmutableMap;
@class ComGoogleCommonCollectUnmodifiableIterator;
@class IOSClass;
@class JavaUtilEnumMap;
@class JavaUtilHashMap;
@class JavaUtilIdentityHashMap;
@class JavaUtilLinkedHashMap;
@class JavaUtilProperties;
@class JavaUtilTreeMap;
@protocol ComGoogleCommonBaseFunction;
@protocol ComGoogleCommonBasePredicate;
@protocol ComGoogleCommonCollectBiMap;
@protocol ComGoogleCommonCollectMapDifference;
@protocol ComGoogleCommonCollectMaps_EntryTransformer;
@protocol ComGoogleCommonCollectSortedMapDifference;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilComparator;
@protocol JavaUtilConcurrentConcurrentMap;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;
@protocol JavaUtilMap_Entry;
@protocol JavaUtilNavigableMap;
@protocol JavaUtilNavigableSet;
@protocol JavaUtilSet;
@protocol JavaUtilSortedMap;
@protocol JavaUtilSortedSet;

@interface ComGoogleCommonCollectMaps : NSObject

#pragma mark Public

+ (ComGoogleCommonBaseConverter *)asConverterWithComGoogleCommonCollectBiMap:(id<ComGoogleCommonCollectBiMap>)bimap;

+ (id<JavaUtilNavigableMap>)asMapWithJavaUtilNavigableSet:(id<JavaUtilNavigableSet>)set
                          withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<JavaUtilMap>)asMapWithJavaUtilSet:(id<JavaUtilSet>)set
        withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<JavaUtilSortedMap>)asMapWithJavaUtilSortedSet:(id<JavaUtilSortedSet>)set
                    withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<ComGoogleCommonCollectMapDifference>)differenceWithJavaUtilMap:(id<JavaUtilMap>)left
                                                     withJavaUtilMap:(id<JavaUtilMap>)right;

+ (id<ComGoogleCommonCollectMapDifference>)differenceWithJavaUtilMap:(id<JavaUtilMap>)left
                                                     withJavaUtilMap:(id<JavaUtilMap>)right
                                  withComGoogleCommonBaseEquivalence:(ComGoogleCommonBaseEquivalence *)valueEquivalence;

+ (id<ComGoogleCommonCollectSortedMapDifference>)differenceWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)left
                                                                 withJavaUtilMap:(id<JavaUtilMap>)right;

+ (id<ComGoogleCommonCollectBiMap>)filterEntriesWithComGoogleCommonCollectBiMap:(id<ComGoogleCommonCollectBiMap>)unfiltered
                                               withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)entryPredicate;

+ (id<JavaUtilMap>)filterEntriesWithJavaUtilMap:(id<JavaUtilMap>)unfiltered
               withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)entryPredicate;

+ (id<JavaUtilNavigableMap>)filterEntriesWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)unfiltered
                                 withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)entryPredicate;

+ (id<JavaUtilSortedMap>)filterEntriesWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)unfiltered
                           withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)entryPredicate;

+ (id<ComGoogleCommonCollectBiMap>)filterKeysWithComGoogleCommonCollectBiMap:(id<ComGoogleCommonCollectBiMap>)unfiltered
                                            withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)keyPredicate;

+ (id<JavaUtilMap>)filterKeysWithJavaUtilMap:(id<JavaUtilMap>)unfiltered
            withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)keyPredicate;

+ (id<JavaUtilNavigableMap>)filterKeysWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)unfiltered
                              withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)keyPredicate;

+ (id<JavaUtilSortedMap>)filterKeysWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)unfiltered
                        withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)keyPredicate;

+ (id<ComGoogleCommonCollectBiMap>)filterValuesWithComGoogleCommonCollectBiMap:(id<ComGoogleCommonCollectBiMap>)unfiltered
                                              withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)valuePredicate;

+ (id<JavaUtilMap>)filterValuesWithJavaUtilMap:(id<JavaUtilMap>)unfiltered
              withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)valuePredicate;

+ (id<JavaUtilNavigableMap>)filterValuesWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)unfiltered
                                withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)valuePredicate;

+ (id<JavaUtilSortedMap>)filterValuesWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)unfiltered
                          withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)valuePredicate;

+ (ComGoogleCommonCollectImmutableMap *)fromPropertiesWithJavaUtilProperties:(JavaUtilProperties *)properties;

+ (id<JavaUtilMap_Entry>)immutableEntryWithId:(id)key
                                       withId:(id)value;

+ (ComGoogleCommonCollectImmutableMap *)immutableEnumMapWithJavaUtilMap:(id<JavaUtilMap>)map;

+ (id<JavaUtilConcurrentConcurrentMap>)newConcurrentMap OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilEnumMap *)newEnumMapWithIOSClass:(IOSClass *)type OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilEnumMap *)newEnumMapWithJavaUtilMap:(id<JavaUtilMap>)map OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilHashMap *)newHashMap OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilHashMap *)newHashMapWithJavaUtilMap:(id<JavaUtilMap>)map OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilHashMap *)newHashMapWithExpectedSizeWithInt:(jint)expectedSize OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilIdentityHashMap *)newIdentityHashMap OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilLinkedHashMap *)newLinkedHashMap OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilLinkedHashMap *)newLinkedHashMapWithJavaUtilMap:(id<JavaUtilMap>)map OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilLinkedHashMap *)newLinkedHashMapWithExpectedSizeWithInt:(jint)expectedSize OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilTreeMap *)newTreeMap OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilTreeMap *)newTreeMapWithJavaUtilComparator:(id<JavaUtilComparator>)comparator OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilTreeMap *)newTreeMapWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)map OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonCollectBiMap>)synchronizedBiMapWithComGoogleCommonCollectBiMap:(id<ComGoogleCommonCollectBiMap>)bimap;

+ (id<JavaUtilNavigableMap>)synchronizedNavigableMapWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)navigableMap;

+ (ComGoogleCommonCollectImmutableMap *)toMapWithJavaLangIterable:(id<JavaLangIterable>)keys
                                  withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)valueFunction;

+ (ComGoogleCommonCollectImmutableMap *)toMapWithJavaUtilIterator:(id<JavaUtilIterator>)keys
                                  withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)valueFunction;

+ (id<JavaUtilMap>)transformEntriesWithJavaUtilMap:(id<JavaUtilMap>)fromMap
   withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (id<JavaUtilNavigableMap>)transformEntriesWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)fromMap
                     withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (id<JavaUtilSortedMap>)transformEntriesWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)fromMap
               withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (id<JavaUtilMap>)transformValuesWithJavaUtilMap:(id<JavaUtilMap>)fromMap
                  withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<JavaUtilNavigableMap>)transformValuesWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)fromMap
                                    withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<JavaUtilSortedMap>)transformValuesWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)fromMap
                              withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (ComGoogleCommonCollectImmutableMap *)uniqueIndexWithJavaLangIterable:(id<JavaLangIterable>)values
                                        withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)keyFunction;

+ (ComGoogleCommonCollectImmutableMap *)uniqueIndexWithJavaUtilIterator:(id<JavaUtilIterator>)values
                                        withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)keyFunction;

+ (id<ComGoogleCommonCollectBiMap>)unmodifiableBiMapWithComGoogleCommonCollectBiMap:(id<ComGoogleCommonCollectBiMap>)bimap;

+ (id<JavaUtilNavigableMap>)unmodifiableNavigableMapWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)map;

#pragma mark Package-Private

+ (id<ComGoogleCommonBaseFunction>)asEntryToEntryFunctionWithComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (id<ComGoogleCommonBaseFunction>)asEntryToValueFunctionWithComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (id<ComGoogleCommonCollectMaps_EntryTransformer>)asEntryTransformerWithComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<JavaUtilIterator>)asMapEntryIteratorWithJavaUtilSet:(id<JavaUtilSet>)set
                          withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<JavaUtilSortedMap>)asMapSortedIgnoreNavigableWithJavaUtilSortedSet:(id<JavaUtilSortedSet>)set
                                         withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<ComGoogleCommonBaseFunction>)asValueToValueFunctionWithComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer
                                                                                                  withId:(id)key;

+ (jint)capacityWithInt:(jint)expectedSize;

+ (jboolean)containsEntryImplWithJavaUtilCollection:(id<JavaUtilCollection>)c
                                             withId:(id)o;

+ (jboolean)containsKeyImplWithJavaUtilMap:(id<JavaUtilMap>)map
                                    withId:(id)key;

+ (jboolean)containsValueImplWithJavaUtilMap:(id<JavaUtilMap>)map
                                      withId:(id)value;

+ (jboolean)equalsImplWithJavaUtilMap:(id<JavaUtilMap>)map
                               withId:(id)object;

+ (id<JavaUtilSortedMap>)filterSortedIgnoreNavigableWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)unfiltered
                                         withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)entryPredicate;

+ (ComGoogleCommonCollectImmutableMap *)indexMapWithJavaUtilCollection:(id<JavaUtilCollection>)list;

+ (id<ComGoogleCommonBaseFunction>)keyFunction;

+ (id<JavaUtilIterator>)keyIteratorWithJavaUtilIterator:(id<JavaUtilIterator>)entryIterator;

+ (id)keyOrNullWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_;

+ (id<ComGoogleCommonBasePredicate>)keyPredicateOnEntriesWithComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)keyPredicate;

+ (id<JavaUtilComparator>)orNaturalOrderWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

+ (void)putAllImplWithJavaUtilMap:(id<JavaUtilMap>)self_
                  withJavaUtilMap:(id<JavaUtilMap>)map;

+ (jboolean)removeEntryImplWithJavaUtilCollection:(id<JavaUtilCollection>)c
                                           withId:(id)o;

+ (jboolean)safeContainsKeyWithJavaUtilMap:(id<JavaUtilMap>)map
                                    withId:(id)key;

+ (id)safeGetWithJavaUtilMap:(id<JavaUtilMap>)map
                      withId:(id)key;

+ (id)safeRemoveWithJavaUtilMap:(id<JavaUtilMap>)map
                         withId:(id)key;

+ (NSString *)toStringImplWithJavaUtilMap:(id<JavaUtilMap>)map;

+ (id<JavaUtilSortedMap>)transformEntriesIgnoreNavigableWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)fromMap
                              withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (id<JavaUtilMap_Entry>)transformEntryWithComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer
                                                                 withJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_;

+ (id<JavaUtilMap_Entry>)unmodifiableEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_;

+ (ComGoogleCommonCollectUnmodifiableIterator *)unmodifiableEntryIteratorWithJavaUtilIterator:(id<JavaUtilIterator>)entryIterator;

+ (id<JavaUtilSet>)unmodifiableEntrySetWithJavaUtilSet:(id<JavaUtilSet>)entrySet;

+ (id<ComGoogleCommonBaseFunction>)valueFunction;

+ (id<JavaUtilIterator>)valueIteratorWithJavaUtilIterator:(id<JavaUtilIterator>)entryIterator;

+ (id)valueOrNullWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_;

+ (id<ComGoogleCommonBasePredicate>)valuePredicateOnEntriesWithComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)valuePredicate;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonCollectMaps)

inline ComGoogleCommonBaseJoiner_MapJoiner *ComGoogleCommonCollectMaps_get_STANDARD_JOINER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonBaseJoiner_MapJoiner *ComGoogleCommonCollectMaps_STANDARD_JOINER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonCollectMaps, STANDARD_JOINER, ComGoogleCommonBaseJoiner_MapJoiner *)

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonCollectMaps_keyFunction();

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonCollectMaps_valueFunction();

FOUNDATION_EXPORT id<JavaUtilIterator> ComGoogleCommonCollectMaps_keyIteratorWithJavaUtilIterator_(id<JavaUtilIterator> entryIterator);

FOUNDATION_EXPORT id<JavaUtilIterator> ComGoogleCommonCollectMaps_valueIteratorWithJavaUtilIterator_(id<JavaUtilIterator> entryIterator);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableMap *ComGoogleCommonCollectMaps_immutableEnumMapWithJavaUtilMap_(id<JavaUtilMap> map);

FOUNDATION_EXPORT JavaUtilHashMap *ComGoogleCommonCollectMaps_newHashMap();

FOUNDATION_EXPORT JavaUtilHashMap *ComGoogleCommonCollectMaps_newHashMapWithExpectedSizeWithInt_(jint expectedSize);

FOUNDATION_EXPORT jint ComGoogleCommonCollectMaps_capacityWithInt_(jint expectedSize);

FOUNDATION_EXPORT JavaUtilHashMap *ComGoogleCommonCollectMaps_newHashMapWithJavaUtilMap_(id<JavaUtilMap> map);

FOUNDATION_EXPORT JavaUtilLinkedHashMap *ComGoogleCommonCollectMaps_newLinkedHashMap();

FOUNDATION_EXPORT JavaUtilLinkedHashMap *ComGoogleCommonCollectMaps_newLinkedHashMapWithExpectedSizeWithInt_(jint expectedSize);

FOUNDATION_EXPORT JavaUtilLinkedHashMap *ComGoogleCommonCollectMaps_newLinkedHashMapWithJavaUtilMap_(id<JavaUtilMap> map);

FOUNDATION_EXPORT id<JavaUtilConcurrentConcurrentMap> ComGoogleCommonCollectMaps_newConcurrentMap();

FOUNDATION_EXPORT JavaUtilTreeMap *ComGoogleCommonCollectMaps_newTreeMap();

FOUNDATION_EXPORT JavaUtilTreeMap *ComGoogleCommonCollectMaps_newTreeMapWithJavaUtilSortedMap_(id<JavaUtilSortedMap> map);

FOUNDATION_EXPORT JavaUtilTreeMap *ComGoogleCommonCollectMaps_newTreeMapWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT JavaUtilEnumMap *ComGoogleCommonCollectMaps_newEnumMapWithIOSClass_(IOSClass *type);

FOUNDATION_EXPORT JavaUtilEnumMap *ComGoogleCommonCollectMaps_newEnumMapWithJavaUtilMap_(id<JavaUtilMap> map);

FOUNDATION_EXPORT JavaUtilIdentityHashMap *ComGoogleCommonCollectMaps_newIdentityHashMap();

FOUNDATION_EXPORT id<ComGoogleCommonCollectMapDifference> ComGoogleCommonCollectMaps_differenceWithJavaUtilMap_withJavaUtilMap_(id<JavaUtilMap> left, id<JavaUtilMap> right);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMapDifference> ComGoogleCommonCollectMaps_differenceWithJavaUtilMap_withJavaUtilMap_withComGoogleCommonBaseEquivalence_(id<JavaUtilMap> left, id<JavaUtilMap> right, ComGoogleCommonBaseEquivalence *valueEquivalence);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSortedMapDifference> ComGoogleCommonCollectMaps_differenceWithJavaUtilSortedMap_withJavaUtilMap_(id<JavaUtilSortedMap> left, id<JavaUtilMap> right);

FOUNDATION_EXPORT id<JavaUtilComparator> ComGoogleCommonCollectMaps_orNaturalOrderWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT id<JavaUtilMap> ComGoogleCommonCollectMaps_asMapWithJavaUtilSet_withComGoogleCommonBaseFunction_(id<JavaUtilSet> set, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_asMapWithJavaUtilSortedSet_withComGoogleCommonBaseFunction_(id<JavaUtilSortedSet> set, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_asMapSortedIgnoreNavigableWithJavaUtilSortedSet_withComGoogleCommonBaseFunction_(id<JavaUtilSortedSet> set, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_asMapWithJavaUtilNavigableSet_withComGoogleCommonBaseFunction_(id<JavaUtilNavigableSet> set, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<JavaUtilIterator> ComGoogleCommonCollectMaps_asMapEntryIteratorWithJavaUtilSet_withComGoogleCommonBaseFunction_(id<JavaUtilSet> set, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableMap *ComGoogleCommonCollectMaps_toMapWithJavaLangIterable_withComGoogleCommonBaseFunction_(id<JavaLangIterable> keys, id<ComGoogleCommonBaseFunction> valueFunction);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableMap *ComGoogleCommonCollectMaps_toMapWithJavaUtilIterator_withComGoogleCommonBaseFunction_(id<JavaUtilIterator> keys, id<ComGoogleCommonBaseFunction> valueFunction);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableMap *ComGoogleCommonCollectMaps_uniqueIndexWithJavaLangIterable_withComGoogleCommonBaseFunction_(id<JavaLangIterable> values, id<ComGoogleCommonBaseFunction> keyFunction);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableMap *ComGoogleCommonCollectMaps_uniqueIndexWithJavaUtilIterator_withComGoogleCommonBaseFunction_(id<JavaUtilIterator> values, id<ComGoogleCommonBaseFunction> keyFunction);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableMap *ComGoogleCommonCollectMaps_fromPropertiesWithJavaUtilProperties_(JavaUtilProperties *properties);

FOUNDATION_EXPORT id<JavaUtilMap_Entry> ComGoogleCommonCollectMaps_immutableEntryWithId_withId_(id key, id value);

FOUNDATION_EXPORT id<JavaUtilSet> ComGoogleCommonCollectMaps_unmodifiableEntrySetWithJavaUtilSet_(id<JavaUtilSet> entrySet);

FOUNDATION_EXPORT id<JavaUtilMap_Entry> ComGoogleCommonCollectMaps_unmodifiableEntryWithJavaUtilMap_Entry_(id<JavaUtilMap_Entry> entry_);

FOUNDATION_EXPORT ComGoogleCommonCollectUnmodifiableIterator *ComGoogleCommonCollectMaps_unmodifiableEntryIteratorWithJavaUtilIterator_(id<JavaUtilIterator> entryIterator);

FOUNDATION_EXPORT ComGoogleCommonBaseConverter *ComGoogleCommonCollectMaps_asConverterWithComGoogleCommonCollectBiMap_(id<ComGoogleCommonCollectBiMap> bimap);

FOUNDATION_EXPORT id<ComGoogleCommonCollectBiMap> ComGoogleCommonCollectMaps_synchronizedBiMapWithComGoogleCommonCollectBiMap_(id<ComGoogleCommonCollectBiMap> bimap);

FOUNDATION_EXPORT id<ComGoogleCommonCollectBiMap> ComGoogleCommonCollectMaps_unmodifiableBiMapWithComGoogleCommonCollectBiMap_(id<ComGoogleCommonCollectBiMap> bimap);

FOUNDATION_EXPORT id<JavaUtilMap> ComGoogleCommonCollectMaps_transformValuesWithJavaUtilMap_withComGoogleCommonBaseFunction_(id<JavaUtilMap> fromMap, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_transformValuesWithJavaUtilSortedMap_withComGoogleCommonBaseFunction_(id<JavaUtilSortedMap> fromMap, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_transformValuesWithJavaUtilNavigableMap_withComGoogleCommonBaseFunction_(id<JavaUtilNavigableMap> fromMap, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<JavaUtilMap> ComGoogleCommonCollectMaps_transformEntriesWithJavaUtilMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_transformEntriesWithJavaUtilSortedMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilSortedMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_transformEntriesWithJavaUtilNavigableMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilNavigableMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_transformEntriesIgnoreNavigableWithJavaUtilSortedMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilSortedMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMaps_EntryTransformer> ComGoogleCommonCollectMaps_asEntryTransformerWithComGoogleCommonBaseFunction_(id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonCollectMaps_asValueToValueFunctionWithComGoogleCommonCollectMaps_EntryTransformer_withId_(id<ComGoogleCommonCollectMaps_EntryTransformer> transformer, id key);

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonCollectMaps_asEntryToValueFunctionWithComGoogleCommonCollectMaps_EntryTransformer_(id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT id<JavaUtilMap_Entry> ComGoogleCommonCollectMaps_transformEntryWithComGoogleCommonCollectMaps_EntryTransformer_withJavaUtilMap_Entry_(id<ComGoogleCommonCollectMaps_EntryTransformer> transformer, id<JavaUtilMap_Entry> entry_);

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonCollectMaps_asEntryToEntryFunctionWithComGoogleCommonCollectMaps_EntryTransformer_(id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT id<ComGoogleCommonBasePredicate> ComGoogleCommonCollectMaps_keyPredicateOnEntriesWithComGoogleCommonBasePredicate_(id<ComGoogleCommonBasePredicate> keyPredicate);

FOUNDATION_EXPORT id<ComGoogleCommonBasePredicate> ComGoogleCommonCollectMaps_valuePredicateOnEntriesWithComGoogleCommonBasePredicate_(id<ComGoogleCommonBasePredicate> valuePredicate);

FOUNDATION_EXPORT id<JavaUtilMap> ComGoogleCommonCollectMaps_filterKeysWithJavaUtilMap_withComGoogleCommonBasePredicate_(id<JavaUtilMap> unfiltered, id<ComGoogleCommonBasePredicate> keyPredicate);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_filterKeysWithJavaUtilSortedMap_withComGoogleCommonBasePredicate_(id<JavaUtilSortedMap> unfiltered, id<ComGoogleCommonBasePredicate> keyPredicate);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_filterKeysWithJavaUtilNavigableMap_withComGoogleCommonBasePredicate_(id<JavaUtilNavigableMap> unfiltered, id<ComGoogleCommonBasePredicate> keyPredicate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectBiMap> ComGoogleCommonCollectMaps_filterKeysWithComGoogleCommonCollectBiMap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectBiMap> unfiltered, id<ComGoogleCommonBasePredicate> keyPredicate);

FOUNDATION_EXPORT id<JavaUtilMap> ComGoogleCommonCollectMaps_filterValuesWithJavaUtilMap_withComGoogleCommonBasePredicate_(id<JavaUtilMap> unfiltered, id<ComGoogleCommonBasePredicate> valuePredicate);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_filterValuesWithJavaUtilSortedMap_withComGoogleCommonBasePredicate_(id<JavaUtilSortedMap> unfiltered, id<ComGoogleCommonBasePredicate> valuePredicate);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_filterValuesWithJavaUtilNavigableMap_withComGoogleCommonBasePredicate_(id<JavaUtilNavigableMap> unfiltered, id<ComGoogleCommonBasePredicate> valuePredicate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectBiMap> ComGoogleCommonCollectMaps_filterValuesWithComGoogleCommonCollectBiMap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectBiMap> unfiltered, id<ComGoogleCommonBasePredicate> valuePredicate);

FOUNDATION_EXPORT id<JavaUtilMap> ComGoogleCommonCollectMaps_filterEntriesWithJavaUtilMap_withComGoogleCommonBasePredicate_(id<JavaUtilMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_filterEntriesWithJavaUtilSortedMap_withComGoogleCommonBasePredicate_(id<JavaUtilSortedMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);

FOUNDATION_EXPORT id<JavaUtilSortedMap> ComGoogleCommonCollectMaps_filterSortedIgnoreNavigableWithJavaUtilSortedMap_withComGoogleCommonBasePredicate_(id<JavaUtilSortedMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_filterEntriesWithJavaUtilNavigableMap_withComGoogleCommonBasePredicate_(id<JavaUtilNavigableMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectBiMap> ComGoogleCommonCollectMaps_filterEntriesWithComGoogleCommonCollectBiMap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectBiMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_unmodifiableNavigableMapWithJavaUtilNavigableMap_(id<JavaUtilNavigableMap> map);

FOUNDATION_EXPORT id<JavaUtilNavigableMap> ComGoogleCommonCollectMaps_synchronizedNavigableMapWithJavaUtilNavigableMap_(id<JavaUtilNavigableMap> navigableMap);

FOUNDATION_EXPORT id ComGoogleCommonCollectMaps_safeGetWithJavaUtilMap_withId_(id<JavaUtilMap> map, id key);

FOUNDATION_EXPORT jboolean ComGoogleCommonCollectMaps_safeContainsKeyWithJavaUtilMap_withId_(id<JavaUtilMap> map, id key);

FOUNDATION_EXPORT id ComGoogleCommonCollectMaps_safeRemoveWithJavaUtilMap_withId_(id<JavaUtilMap> map, id key);

FOUNDATION_EXPORT jboolean ComGoogleCommonCollectMaps_containsKeyImplWithJavaUtilMap_withId_(id<JavaUtilMap> map, id key);

FOUNDATION_EXPORT jboolean ComGoogleCommonCollectMaps_containsValueImplWithJavaUtilMap_withId_(id<JavaUtilMap> map, id value);

FOUNDATION_EXPORT jboolean ComGoogleCommonCollectMaps_containsEntryImplWithJavaUtilCollection_withId_(id<JavaUtilCollection> c, id o);

FOUNDATION_EXPORT jboolean ComGoogleCommonCollectMaps_removeEntryImplWithJavaUtilCollection_withId_(id<JavaUtilCollection> c, id o);

FOUNDATION_EXPORT jboolean ComGoogleCommonCollectMaps_equalsImplWithJavaUtilMap_withId_(id<JavaUtilMap> map, id object);

FOUNDATION_EXPORT NSString *ComGoogleCommonCollectMaps_toStringImplWithJavaUtilMap_(id<JavaUtilMap> map);

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_putAllImplWithJavaUtilMap_withJavaUtilMap_(id<JavaUtilMap> self_, id<JavaUtilMap> map);

FOUNDATION_EXPORT id ComGoogleCommonCollectMaps_keyOrNullWithJavaUtilMap_Entry_(id<JavaUtilMap_Entry> entry_);

FOUNDATION_EXPORT id ComGoogleCommonCollectMaps_valueOrNullWithJavaUtilMap_Entry_(id<JavaUtilMap_Entry> entry_);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableMap *ComGoogleCommonCollectMaps_indexMapWithJavaUtilCollection_(id<JavaUtilCollection> list);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps)

#endif

#if !defined (ComGoogleCommonCollectMaps_MapDifferenceImpl_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_MapDifferenceImpl))
#define ComGoogleCommonCollectMaps_MapDifferenceImpl_

#define RESTRICT_ComGoogleCommonCollectMapDifference 1
#define INCLUDE_ComGoogleCommonCollectMapDifference 1
#include "com/google/common/collect/MapDifference.h"

@protocol JavaUtilMap;

@interface ComGoogleCommonCollectMaps_MapDifferenceImpl : NSObject < ComGoogleCommonCollectMapDifference > {
 @public
  id<JavaUtilMap> onlyOnLeft_;
  id<JavaUtilMap> onlyOnRight_;
  id<JavaUtilMap> onBoth_;
  id<JavaUtilMap> differences_;
}

#pragma mark Public

- (jboolean)areEqual;

- (id<JavaUtilMap>)entriesDiffering;

- (id<JavaUtilMap>)entriesInCommon;

- (id<JavaUtilMap>)entriesOnlyOnLeft;

- (id<JavaUtilMap>)entriesOnlyOnRight;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)onlyOnLeft
                    withJavaUtilMap:(id<JavaUtilMap>)onlyOnRight
                    withJavaUtilMap:(id<JavaUtilMap>)onBoth
                    withJavaUtilMap:(id<JavaUtilMap>)differences;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_MapDifferenceImpl)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_MapDifferenceImpl, onlyOnLeft_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_MapDifferenceImpl, onlyOnRight_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_MapDifferenceImpl, onBoth_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_MapDifferenceImpl, differences_, id<JavaUtilMap>)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_MapDifferenceImpl_initWithJavaUtilMap_withJavaUtilMap_withJavaUtilMap_withJavaUtilMap_(ComGoogleCommonCollectMaps_MapDifferenceImpl *self, id<JavaUtilMap> onlyOnLeft, id<JavaUtilMap> onlyOnRight, id<JavaUtilMap> onBoth, id<JavaUtilMap> differences);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_MapDifferenceImpl *new_ComGoogleCommonCollectMaps_MapDifferenceImpl_initWithJavaUtilMap_withJavaUtilMap_withJavaUtilMap_withJavaUtilMap_(id<JavaUtilMap> onlyOnLeft, id<JavaUtilMap> onlyOnRight, id<JavaUtilMap> onBoth, id<JavaUtilMap> differences) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_MapDifferenceImpl *create_ComGoogleCommonCollectMaps_MapDifferenceImpl_initWithJavaUtilMap_withJavaUtilMap_withJavaUtilMap_withJavaUtilMap_(id<JavaUtilMap> onlyOnLeft, id<JavaUtilMap> onlyOnRight, id<JavaUtilMap> onBoth, id<JavaUtilMap> differences);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_MapDifferenceImpl)

#endif

#if !defined (ComGoogleCommonCollectMaps_ValueDifferenceImpl_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_ValueDifferenceImpl))
#define ComGoogleCommonCollectMaps_ValueDifferenceImpl_

#define RESTRICT_ComGoogleCommonCollectMapDifference 1
#define INCLUDE_ComGoogleCommonCollectMapDifference_ValueDifference 1
#include "com/google/common/collect/MapDifference.h"

@interface ComGoogleCommonCollectMaps_ValueDifferenceImpl : NSObject < ComGoogleCommonCollectMapDifference_ValueDifference >

#pragma mark Public

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (id)leftValue;

- (id)rightValue;

- (NSString *)description;

#pragma mark Package-Private

+ (id<ComGoogleCommonCollectMapDifference_ValueDifference>)createWithId:(id)left
                                                                 withId:(id)right;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_ValueDifferenceImpl)

FOUNDATION_EXPORT id<ComGoogleCommonCollectMapDifference_ValueDifference> ComGoogleCommonCollectMaps_ValueDifferenceImpl_createWithId_withId_(id left, id right);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_ValueDifferenceImpl)

#endif

#if !defined (ComGoogleCommonCollectMaps_SortedMapDifferenceImpl_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_SortedMapDifferenceImpl))
#define ComGoogleCommonCollectMaps_SortedMapDifferenceImpl_

#define RESTRICT_ComGoogleCommonCollectSortedMapDifference 1
#define INCLUDE_ComGoogleCommonCollectSortedMapDifference 1
#include "com/google/common/collect/SortedMapDifference.h"

@protocol JavaUtilSortedMap;

@interface ComGoogleCommonCollectMaps_SortedMapDifferenceImpl : ComGoogleCommonCollectMaps_MapDifferenceImpl < ComGoogleCommonCollectSortedMapDifference >

#pragma mark Public

- (id<JavaUtilSortedMap>)entriesDiffering;

- (id<JavaUtilSortedMap>)entriesInCommon;

- (id<JavaUtilSortedMap>)entriesOnlyOnLeft;

- (id<JavaUtilSortedMap>)entriesOnlyOnRight;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)onlyOnLeft
                    withJavaUtilSortedMap:(id<JavaUtilSortedMap>)onlyOnRight
                    withJavaUtilSortedMap:(id<JavaUtilSortedMap>)onBoth
                    withJavaUtilSortedMap:(id<JavaUtilSortedMap>)differences;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_SortedMapDifferenceImpl)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_SortedMapDifferenceImpl_initWithJavaUtilSortedMap_withJavaUtilSortedMap_withJavaUtilSortedMap_withJavaUtilSortedMap_(ComGoogleCommonCollectMaps_SortedMapDifferenceImpl *self, id<JavaUtilSortedMap> onlyOnLeft, id<JavaUtilSortedMap> onlyOnRight, id<JavaUtilSortedMap> onBoth, id<JavaUtilSortedMap> differences);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_SortedMapDifferenceImpl *new_ComGoogleCommonCollectMaps_SortedMapDifferenceImpl_initWithJavaUtilSortedMap_withJavaUtilSortedMap_withJavaUtilSortedMap_withJavaUtilSortedMap_(id<JavaUtilSortedMap> onlyOnLeft, id<JavaUtilSortedMap> onlyOnRight, id<JavaUtilSortedMap> onBoth, id<JavaUtilSortedMap> differences) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_SortedMapDifferenceImpl *create_ComGoogleCommonCollectMaps_SortedMapDifferenceImpl_initWithJavaUtilSortedMap_withJavaUtilSortedMap_withJavaUtilSortedMap_withJavaUtilSortedMap_(id<JavaUtilSortedMap> onlyOnLeft, id<JavaUtilSortedMap> onlyOnRight, id<JavaUtilSortedMap> onBoth, id<JavaUtilSortedMap> differences);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_SortedMapDifferenceImpl)

#endif

#if !defined (ComGoogleCommonCollectMaps_ViewCachingAbstractMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_ViewCachingAbstractMap))
#define ComGoogleCommonCollectMaps_ViewCachingAbstractMap_

#define RESTRICT_JavaUtilAbstractMap 1
#define INCLUDE_JavaUtilAbstractMap 1
#include "java/util/AbstractMap.h"

@protocol JavaUtilCollection;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectMaps_ViewCachingAbstractMap : JavaUtilAbstractMap

#pragma mark Public

- (id<JavaUtilSet>)entrySet;

- (id<JavaUtilSet>)keySet;

- (id<JavaUtilCollection>)values;

#pragma mark Package-Private

- (instancetype)init;

- (id<JavaUtilSet>)createEntrySet;

- (id<JavaUtilSet>)createKeySet;

- (id<JavaUtilCollection>)createValues;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_ViewCachingAbstractMap)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_ViewCachingAbstractMap_init(ComGoogleCommonCollectMaps_ViewCachingAbstractMap *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_ViewCachingAbstractMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_EntrySet_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_EntrySet))
#define ComGoogleCommonCollectMaps_EntrySet_

#define RESTRICT_ComGoogleCommonCollectSets 1
#define INCLUDE_ComGoogleCommonCollectSets_ImprovedAbstractSet 1
#include "com/google/common/collect/Sets.h"

@protocol JavaUtilCollection;
@protocol JavaUtilMap;

@interface ComGoogleCommonCollectMaps_EntrySet : ComGoogleCommonCollectSets_ImprovedAbstractSet

#pragma mark Public

- (void)clear;

- (jboolean)containsWithId:(id)o;

- (jboolean)isEmpty;

- (jboolean)removeWithId:(id)o;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (jint)size;

#pragma mark Package-Private

- (instancetype)init;

- (id<JavaUtilMap>)map;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_EntrySet)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_EntrySet_init(ComGoogleCommonCollectMaps_EntrySet *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_EntrySet)

#endif

#if !defined (ComGoogleCommonCollectMaps_UnmodifiableEntries_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_UnmodifiableEntries))
#define ComGoogleCommonCollectMaps_UnmodifiableEntries_

#define RESTRICT_ComGoogleCommonCollectForwardingCollection 1
#define INCLUDE_ComGoogleCommonCollectForwardingCollection 1
#include "com/google/common/collect/ForwardingCollection.h"

@class IOSObjectArray;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;

@interface ComGoogleCommonCollectMaps_UnmodifiableEntries : ComGoogleCommonCollectForwardingCollection

#pragma mark Public

- (id<JavaUtilIterator>)iterator;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

#pragma mark Protected

- (id<JavaUtilCollection>)delegate;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)entries;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_UnmodifiableEntries)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_UnmodifiableEntries_initWithJavaUtilCollection_(ComGoogleCommonCollectMaps_UnmodifiableEntries *self, id<JavaUtilCollection> entries);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableEntries *new_ComGoogleCommonCollectMaps_UnmodifiableEntries_initWithJavaUtilCollection_(id<JavaUtilCollection> entries) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableEntries *create_ComGoogleCommonCollectMaps_UnmodifiableEntries_initWithJavaUtilCollection_(id<JavaUtilCollection> entries);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_UnmodifiableEntries)

#endif

#if !defined (ComGoogleCommonCollectMaps_UnmodifiableEntrySet_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_UnmodifiableEntrySet))
#define ComGoogleCommonCollectMaps_UnmodifiableEntrySet_

#define RESTRICT_JavaUtilSet 1
#define INCLUDE_JavaUtilSet 1
#include "java/util/Set.h"

@protocol JavaUtilSpliterator;

@interface ComGoogleCommonCollectMaps_UnmodifiableEntrySet : ComGoogleCommonCollectMaps_UnmodifiableEntries < JavaUtilSet >

#pragma mark Public

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilSet:(id<JavaUtilSet>)entries;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_UnmodifiableEntrySet)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_UnmodifiableEntrySet_initWithJavaUtilSet_(ComGoogleCommonCollectMaps_UnmodifiableEntrySet *self, id<JavaUtilSet> entries);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableEntrySet *new_ComGoogleCommonCollectMaps_UnmodifiableEntrySet_initWithJavaUtilSet_(id<JavaUtilSet> entries) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableEntrySet *create_ComGoogleCommonCollectMaps_UnmodifiableEntrySet_initWithJavaUtilSet_(id<JavaUtilSet> entries);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_UnmodifiableEntrySet)

#endif

#if !defined (ComGoogleCommonCollectMaps_EntryTransformer_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_EntryTransformer))
#define ComGoogleCommonCollectMaps_EntryTransformer_

@protocol ComGoogleCommonCollectMaps_EntryTransformer < JavaObject >

- (id)transformEntryWithId:(id)key
                    withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_EntryTransformer)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_EntryTransformer)

#endif

#if !defined (ComGoogleCommonCollectMaps_IteratorBasedAbstractMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_IteratorBasedAbstractMap))
#define ComGoogleCommonCollectMaps_IteratorBasedAbstractMap_

#define RESTRICT_JavaUtilAbstractMap 1
#define INCLUDE_JavaUtilAbstractMap 1
#include "java/util/AbstractMap.h"

@protocol JavaUtilIterator;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectMaps_IteratorBasedAbstractMap : JavaUtilAbstractMap

#pragma mark Public

- (void)clear;

- (id<JavaUtilSet>)entrySet;

- (jint)size;

#pragma mark Package-Private

- (instancetype)init;

- (id<JavaUtilIterator>)entryIterator;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_IteratorBasedAbstractMap)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_IteratorBasedAbstractMap_init(ComGoogleCommonCollectMaps_IteratorBasedAbstractMap *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_IteratorBasedAbstractMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_TransformedEntriesMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_TransformedEntriesMap))
#define ComGoogleCommonCollectMaps_TransformedEntriesMap_

@protocol ComGoogleCommonCollectMaps_EntryTransformer;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectMaps_TransformedEntriesMap : ComGoogleCommonCollectMaps_IteratorBasedAbstractMap {
 @public
  id<JavaUtilMap> fromMap_;
  id<ComGoogleCommonCollectMaps_EntryTransformer> transformer_;
}

#pragma mark Public

- (void)clear;

- (jboolean)containsKeyWithId:(id)key;

- (id)getWithId:(id)key;

- (id<JavaUtilSet>)keySet;

- (id)removeWithId:(id)key;

- (jint)size;

- (id<JavaUtilCollection>)values;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)fromMap
withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

- (id<JavaUtilIterator>)entryIterator;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_TransformedEntriesMap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_TransformedEntriesMap, fromMap_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_TransformedEntriesMap, transformer_, id<ComGoogleCommonCollectMaps_EntryTransformer>)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_TransformedEntriesMap_initWithJavaUtilMap_withComGoogleCommonCollectMaps_EntryTransformer_(ComGoogleCommonCollectMaps_TransformedEntriesMap *self, id<JavaUtilMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_TransformedEntriesMap *new_ComGoogleCommonCollectMaps_TransformedEntriesMap_initWithJavaUtilMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_TransformedEntriesMap *create_ComGoogleCommonCollectMaps_TransformedEntriesMap_initWithJavaUtilMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_TransformedEntriesMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_TransformedEntriesSortedMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_TransformedEntriesSortedMap))
#define ComGoogleCommonCollectMaps_TransformedEntriesSortedMap_

#define RESTRICT_JavaUtilSortedMap 1
#define INCLUDE_JavaUtilSortedMap 1
#include "java/util/SortedMap.h"

@protocol ComGoogleCommonCollectMaps_EntryTransformer;
@protocol JavaUtilComparator;

@interface ComGoogleCommonCollectMaps_TransformedEntriesSortedMap : ComGoogleCommonCollectMaps_TransformedEntriesMap < JavaUtilSortedMap >

#pragma mark Public

- (id<JavaUtilComparator>)comparator;

- (id)firstKey;

- (id<JavaUtilSortedMap>)headMapWithId:(id)toKey;

- (id)lastKey;

- (id<JavaUtilSortedMap>)subMapWithId:(id)fromKey
                               withId:(id)toKey;

- (id<JavaUtilSortedMap>)tailMapWithId:(id)fromKey;

#pragma mark Protected

- (id<JavaUtilSortedMap>)fromMap;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)fromMap
withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_TransformedEntriesSortedMap)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_TransformedEntriesSortedMap_initWithJavaUtilSortedMap_withComGoogleCommonCollectMaps_EntryTransformer_(ComGoogleCommonCollectMaps_TransformedEntriesSortedMap *self, id<JavaUtilSortedMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_TransformedEntriesSortedMap *new_ComGoogleCommonCollectMaps_TransformedEntriesSortedMap_initWithJavaUtilSortedMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilSortedMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_TransformedEntriesSortedMap *create_ComGoogleCommonCollectMaps_TransformedEntriesSortedMap_initWithJavaUtilSortedMap_withComGoogleCommonCollectMaps_EntryTransformer_(id<JavaUtilSortedMap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_TransformedEntriesSortedMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_AbstractFilteredMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_AbstractFilteredMap))
#define ComGoogleCommonCollectMaps_AbstractFilteredMap_

@protocol ComGoogleCommonBasePredicate;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

@interface ComGoogleCommonCollectMaps_AbstractFilteredMap : ComGoogleCommonCollectMaps_ViewCachingAbstractMap {
 @public
  id<JavaUtilMap> unfiltered_;
  id<ComGoogleCommonBasePredicate> predicate_;
}

#pragma mark Public

- (jboolean)containsKeyWithId:(id)key;

- (id)getWithId:(id)key;

- (jboolean)isEmpty;

- (id)putWithId:(id)key
         withId:(id)value;

- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)map;

- (id)removeWithId:(id)key;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)unfiltered
   withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)predicate;

- (jboolean)applyWithId:(id)key
                 withId:(id)value;

- (id<JavaUtilCollection>)createValues;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_AbstractFilteredMap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_AbstractFilteredMap, unfiltered_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_AbstractFilteredMap, predicate_, id<ComGoogleCommonBasePredicate>)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_AbstractFilteredMap_initWithJavaUtilMap_withComGoogleCommonBasePredicate_(ComGoogleCommonCollectMaps_AbstractFilteredMap *self, id<JavaUtilMap> unfiltered, id<ComGoogleCommonBasePredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_AbstractFilteredMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_Values_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_Values))
#define ComGoogleCommonCollectMaps_Values_

#define RESTRICT_JavaUtilAbstractCollection 1
#define INCLUDE_JavaUtilAbstractCollection 1
#include "java/util/AbstractCollection.h"

@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;

@interface ComGoogleCommonCollectMaps_Values : JavaUtilAbstractCollection {
 @public
  __unsafe_unretained id<JavaUtilMap> map_;
}

#pragma mark Public

- (void)clear;

- (jboolean)containsWithId:(id)o;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)o;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (jint)size;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map;

- (id<JavaUtilMap>)map;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_Values)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_Values_initWithJavaUtilMap_(ComGoogleCommonCollectMaps_Values *self, id<JavaUtilMap> map);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_Values *new_ComGoogleCommonCollectMaps_Values_initWithJavaUtilMap_(id<JavaUtilMap> map) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_Values *create_ComGoogleCommonCollectMaps_Values_initWithJavaUtilMap_(id<JavaUtilMap> map);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_Values)

#endif

#if !defined (ComGoogleCommonCollectMaps_FilteredEntryMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_FilteredEntryMap))
#define ComGoogleCommonCollectMaps_FilteredEntryMap_

@protocol ComGoogleCommonBasePredicate;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectMaps_FilteredEntryMap : ComGoogleCommonCollectMaps_AbstractFilteredMap {
 @public
  id<JavaUtilSet> filteredEntrySet_;
}

#pragma mark Protected

- (id<JavaUtilSet>)createEntrySet;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)unfiltered
   withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)entryPredicate;

- (id<JavaUtilSet>)createKeySet;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_FilteredEntryMap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMaps_FilteredEntryMap, filteredEntrySet_, id<JavaUtilSet>)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_FilteredEntryMap_initWithJavaUtilMap_withComGoogleCommonBasePredicate_(ComGoogleCommonCollectMaps_FilteredEntryMap *self, id<JavaUtilMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_FilteredEntryMap *new_ComGoogleCommonCollectMaps_FilteredEntryMap_initWithJavaUtilMap_withComGoogleCommonBasePredicate_(id<JavaUtilMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_FilteredEntryMap *create_ComGoogleCommonCollectMaps_FilteredEntryMap_initWithJavaUtilMap_withComGoogleCommonBasePredicate_(id<JavaUtilMap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_FilteredEntryMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_KeySet_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_KeySet))
#define ComGoogleCommonCollectMaps_KeySet_

#define RESTRICT_ComGoogleCommonCollectSets 1
#define INCLUDE_ComGoogleCommonCollectSets_ImprovedAbstractSet 1
#include "com/google/common/collect/Sets.h"

@protocol JavaUtilIterator;
@protocol JavaUtilMap;

@interface ComGoogleCommonCollectMaps_KeySet : ComGoogleCommonCollectSets_ImprovedAbstractSet {
 @public
  __unsafe_unretained id<JavaUtilMap> map_;
}

#pragma mark Public

- (void)clear;

- (jboolean)containsWithId:(id)o;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)o;

- (jint)size;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map;

- (id<JavaUtilMap>)map;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_KeySet)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_KeySet_initWithJavaUtilMap_(ComGoogleCommonCollectMaps_KeySet *self, id<JavaUtilMap> map);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_KeySet *new_ComGoogleCommonCollectMaps_KeySet_initWithJavaUtilMap_(id<JavaUtilMap> map) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_KeySet *create_ComGoogleCommonCollectMaps_KeySet_initWithJavaUtilMap_(id<JavaUtilMap> map);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_KeySet)

#endif

#if !defined (ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet))
#define ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet_

@class ComGoogleCommonCollectMaps_FilteredEntryMap;
@class IOSObjectArray;
@protocol JavaUtilCollection;

@interface ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet : ComGoogleCommonCollectMaps_KeySet

#pragma mark Public

- (jboolean)removeWithId:(id)o;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

#pragma mark Package-Private

- (instancetype)initWithComGoogleCommonCollectMaps_FilteredEntryMap:(ComGoogleCommonCollectMaps_FilteredEntryMap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet_initWithComGoogleCommonCollectMaps_FilteredEntryMap_(ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet *self, ComGoogleCommonCollectMaps_FilteredEntryMap *outer$);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet *new_ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet_initWithComGoogleCommonCollectMaps_FilteredEntryMap_(ComGoogleCommonCollectMaps_FilteredEntryMap *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet *create_ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet_initWithComGoogleCommonCollectMaps_FilteredEntryMap_(ComGoogleCommonCollectMaps_FilteredEntryMap *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_FilteredEntryMap_KeySet)

#endif

#if !defined (ComGoogleCommonCollectMaps_SortedKeySet_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_SortedKeySet))
#define ComGoogleCommonCollectMaps_SortedKeySet_

#define RESTRICT_JavaUtilSortedSet 1
#define INCLUDE_JavaUtilSortedSet 1
#include "java/util/SortedSet.h"

@protocol JavaUtilComparator;
@protocol JavaUtilSortedMap;
@protocol JavaUtilSpliterator;

@interface ComGoogleCommonCollectMaps_SortedKeySet : ComGoogleCommonCollectMaps_KeySet < JavaUtilSortedSet >

#pragma mark Public

- (id<JavaUtilComparator>)comparator;

- (id)first;

- (id<JavaUtilSortedSet>)headSetWithId:(id)toElement;

- (id)last;

- (id<JavaUtilSortedSet>)subSetWithId:(id)fromElement
                               withId:(id)toElement;

- (id<JavaUtilSortedSet>)tailSetWithId:(id)fromElement;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilSortedMap:(id<JavaUtilSortedMap>)map;

- (id<JavaUtilSortedMap>)map;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_SortedKeySet)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_SortedKeySet_initWithJavaUtilSortedMap_(ComGoogleCommonCollectMaps_SortedKeySet *self, id<JavaUtilSortedMap> map);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_SortedKeySet *new_ComGoogleCommonCollectMaps_SortedKeySet_initWithJavaUtilSortedMap_(id<JavaUtilSortedMap> map) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_SortedKeySet *create_ComGoogleCommonCollectMaps_SortedKeySet_initWithJavaUtilSortedMap_(id<JavaUtilSortedMap> map);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_SortedKeySet)

#endif

#if !defined (ComGoogleCommonCollectMaps_NavigableKeySet_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_NavigableKeySet))
#define ComGoogleCommonCollectMaps_NavigableKeySet_

#define RESTRICT_JavaUtilNavigableSet 1
#define INCLUDE_JavaUtilNavigableSet 1
#include "java/util/NavigableSet.h"

@protocol JavaUtilIterator;
@protocol JavaUtilNavigableMap;
@protocol JavaUtilSortedSet;

@interface ComGoogleCommonCollectMaps_NavigableKeySet : ComGoogleCommonCollectMaps_SortedKeySet < JavaUtilNavigableSet >

#pragma mark Public

- (id)ceilingWithId:(id)e;

- (id<JavaUtilIterator>)descendingIterator;

- (id<JavaUtilNavigableSet>)descendingSet;

- (id)floorWithId:(id)e;

- (id<JavaUtilSortedSet>)headSetWithId:(id)toElement;

- (id<JavaUtilNavigableSet>)headSetWithId:(id)toElement
                              withBoolean:(jboolean)inclusive;

- (id)higherWithId:(id)e;

- (id)lowerWithId:(id)e;

- (id)pollFirst;

- (id)pollLast;

- (id<JavaUtilNavigableSet>)subSetWithId:(id)fromElement
                             withBoolean:(jboolean)fromInclusive
                                  withId:(id)toElement
                             withBoolean:(jboolean)toInclusive;

- (id<JavaUtilSortedSet>)subSetWithId:(id)fromElement
                               withId:(id)toElement;

- (id<JavaUtilSortedSet>)tailSetWithId:(id)fromElement;

- (id<JavaUtilNavigableSet>)tailSetWithId:(id)fromElement
                              withBoolean:(jboolean)inclusive;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)map;

- (id<JavaUtilNavigableMap>)map;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_NavigableKeySet)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_NavigableKeySet_initWithJavaUtilNavigableMap_(ComGoogleCommonCollectMaps_NavigableKeySet *self, id<JavaUtilNavigableMap> map);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_NavigableKeySet *new_ComGoogleCommonCollectMaps_NavigableKeySet_initWithJavaUtilNavigableMap_(id<JavaUtilNavigableMap> map) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_NavigableKeySet *create_ComGoogleCommonCollectMaps_NavigableKeySet_initWithJavaUtilNavigableMap_(id<JavaUtilNavigableMap> map);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_NavigableKeySet)

#endif

#if !defined (ComGoogleCommonCollectMaps_FilteredEntryBiMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_FilteredEntryBiMap))
#define ComGoogleCommonCollectMaps_FilteredEntryBiMap_

#define RESTRICT_ComGoogleCommonCollectBiMap 1
#define INCLUDE_ComGoogleCommonCollectBiMap 1
#include "com/google/common/collect/BiMap.h"

@protocol ComGoogleCommonBasePredicate;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectMaps_FilteredEntryBiMap : ComGoogleCommonCollectMaps_FilteredEntryMap < ComGoogleCommonCollectBiMap >

#pragma mark Public

- (id)forcePutWithId:(id)key
              withId:(id)value;

- (id<ComGoogleCommonCollectBiMap>)inverse;

- (id<JavaUtilSet>)values;

#pragma mark Package-Private

- (instancetype)initWithComGoogleCommonCollectBiMap:(id<ComGoogleCommonCollectBiMap>)delegate
                   withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)predicate;

- (id<ComGoogleCommonCollectBiMap>)unfiltered;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_FilteredEntryBiMap)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_FilteredEntryBiMap_initWithComGoogleCommonCollectBiMap_withComGoogleCommonBasePredicate_(ComGoogleCommonCollectMaps_FilteredEntryBiMap *self, id<ComGoogleCommonCollectBiMap> delegate, id<ComGoogleCommonBasePredicate> predicate);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_FilteredEntryBiMap *new_ComGoogleCommonCollectMaps_FilteredEntryBiMap_initWithComGoogleCommonCollectBiMap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectBiMap> delegate, id<ComGoogleCommonBasePredicate> predicate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_FilteredEntryBiMap *create_ComGoogleCommonCollectMaps_FilteredEntryBiMap_initWithComGoogleCommonCollectBiMap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectBiMap> delegate, id<ComGoogleCommonBasePredicate> predicate);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_FilteredEntryBiMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_UnmodifiableNavigableMap))
#define ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_

#define RESTRICT_ComGoogleCommonCollectForwardingSortedMap 1
#define INCLUDE_ComGoogleCommonCollectForwardingSortedMap 1
#include "com/google/common/collect/ForwardingSortedMap.h"

#define RESTRICT_JavaUtilNavigableMap 1
#define INCLUDE_JavaUtilNavigableMap 1
#include "java/util/NavigableMap.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@protocol JavaUtilMap_Entry;
@protocol JavaUtilNavigableSet;
@protocol JavaUtilSet;
@protocol JavaUtilSortedMap;

@interface ComGoogleCommonCollectMaps_UnmodifiableNavigableMap : ComGoogleCommonCollectForwardingSortedMap < JavaUtilNavigableMap, JavaIoSerializable >

#pragma mark Public

- (id<JavaUtilMap_Entry>)ceilingEntryWithId:(id)key;

- (id)ceilingKeyWithId:(id)key;

- (id<JavaUtilNavigableSet>)descendingKeySet;

- (id<JavaUtilNavigableMap>)descendingMap;

- (id<JavaUtilMap_Entry>)firstEntry;

- (id<JavaUtilMap_Entry>)floorEntryWithId:(id)key;

- (id)floorKeyWithId:(id)key;

- (id<JavaUtilSortedMap>)headMapWithId:(id)toKey;

- (id<JavaUtilNavigableMap>)headMapWithId:(id)toKey
                              withBoolean:(jboolean)inclusive;

- (id<JavaUtilMap_Entry>)higherEntryWithId:(id)key;

- (id)higherKeyWithId:(id)key;

- (id<JavaUtilSet>)keySet;

- (id<JavaUtilMap_Entry>)lastEntry;

- (id<JavaUtilMap_Entry>)lowerEntryWithId:(id)key;

- (id)lowerKeyWithId:(id)key;

- (id<JavaUtilNavigableSet>)navigableKeySet;

- (id<JavaUtilMap_Entry>)pollFirstEntry;

- (id<JavaUtilMap_Entry>)pollLastEntry;

- (id<JavaUtilNavigableMap>)subMapWithId:(id)fromKey
                             withBoolean:(jboolean)fromInclusive
                                  withId:(id)toKey
                             withBoolean:(jboolean)toInclusive;

- (id<JavaUtilSortedMap>)subMapWithId:(id)fromKey
                               withId:(id)toKey;

- (id<JavaUtilSortedMap>)tailMapWithId:(id)fromKey;

- (id<JavaUtilNavigableMap>)tailMapWithId:(id)fromKey
                              withBoolean:(jboolean)inclusive;

#pragma mark Protected

- (id<JavaUtilSortedMap>)delegate;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)delegate;

- (instancetype)initWithJavaUtilNavigableMap:(id<JavaUtilNavigableMap>)delegate
withComGoogleCommonCollectMaps_UnmodifiableNavigableMap:(ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *)descendingMap;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_UnmodifiableNavigableMap)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_initWithJavaUtilNavigableMap_(ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *self, id<JavaUtilNavigableMap> delegate);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *new_ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_initWithJavaUtilNavigableMap_(id<JavaUtilNavigableMap> delegate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *create_ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_initWithJavaUtilNavigableMap_(id<JavaUtilNavigableMap> delegate);

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_initWithJavaUtilNavigableMap_withComGoogleCommonCollectMaps_UnmodifiableNavigableMap_(ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *self, id<JavaUtilNavigableMap> delegate, ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *descendingMap);

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *new_ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_initWithJavaUtilNavigableMap_withComGoogleCommonCollectMaps_UnmodifiableNavigableMap_(id<JavaUtilNavigableMap> delegate, ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *descendingMap) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *create_ComGoogleCommonCollectMaps_UnmodifiableNavigableMap_initWithJavaUtilNavigableMap_withComGoogleCommonCollectMaps_UnmodifiableNavigableMap_(id<JavaUtilNavigableMap> delegate, ComGoogleCommonCollectMaps_UnmodifiableNavigableMap *descendingMap);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_UnmodifiableNavigableMap)

#endif

#if !defined (ComGoogleCommonCollectMaps_DescendingMap_) && (INCLUDE_ALL_ComGoogleCommonCollectMaps || defined(INCLUDE_ComGoogleCommonCollectMaps_DescendingMap))
#define ComGoogleCommonCollectMaps_DescendingMap_

#define RESTRICT_ComGoogleCommonCollectForwardingMap 1
#define INCLUDE_ComGoogleCommonCollectForwardingMap 1
#include "com/google/common/collect/ForwardingMap.h"

#define RESTRICT_JavaUtilNavigableMap 1
#define INCLUDE_JavaUtilNavigableMap 1
#include "java/util/NavigableMap.h"

@protocol JavaUtilCollection;
@protocol JavaUtilComparator;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;
@protocol JavaUtilMap_Entry;
@protocol JavaUtilNavigableSet;
@protocol JavaUtilSet;
@protocol JavaUtilSortedMap;

@interface ComGoogleCommonCollectMaps_DescendingMap : ComGoogleCommonCollectForwardingMap < JavaUtilNavigableMap >

#pragma mark Public

- (id<JavaUtilMap_Entry>)ceilingEntryWithId:(id)key;

- (id)ceilingKeyWithId:(id)key;

- (id<JavaUtilComparator>)comparator;

- (id<JavaUtilNavigableSet>)descendingKeySet;

- (id<JavaUtilNavigableMap>)descendingMap;

- (id<JavaUtilSet>)entrySet;

- (id<JavaUtilMap_Entry>)firstEntry;

- (id)firstKey;

- (id<JavaUtilMap_Entry>)floorEntryWithId:(id)key;

- (id)floorKeyWithId:(id)key;

- (id<JavaUtilSortedMap>)headMapWithId:(id)toKey;

- (id<JavaUtilNavigableMap>)headMapWithId:(id)toKey
                              withBoolean:(jboolean)inclusive;

- (id<JavaUtilMap_Entry>)higherEntryWithId:(id)key;

- (id)higherKeyWithId:(id)key;

- (id<JavaUtilSet>)keySet;

- (id<JavaUtilMap_Entry>)lastEntry;

- (id)lastKey;

- (id<JavaUtilMap_Entry>)lowerEntryWithId:(id)key;

- (id)lowerKeyWithId:(id)key;

- (id<JavaUtilNavigableSet>)navigableKeySet;

- (id<JavaUtilMap_Entry>)pollFirstEntry;

- (id<JavaUtilMap_Entry>)pollLastEntry;

- (id<JavaUtilNavigableMap>)subMapWithId:(id)fromKey
                             withBoolean:(jboolean)fromInclusive
                                  withId:(id)toKey
                             withBoolean:(jboolean)toInclusive;

- (id<JavaUtilSortedMap>)subMapWithId:(id)fromKey
                               withId:(id)toKey;

- (id<JavaUtilSortedMap>)tailMapWithId:(id)fromKey;

- (id<JavaUtilNavigableMap>)tailMapWithId:(id)fromKey
                              withBoolean:(jboolean)inclusive;

- (NSString *)description;

- (id<JavaUtilCollection>)values;

#pragma mark Protected

- (id<JavaUtilMap>)delegate;

#pragma mark Package-Private

- (instancetype)init;

- (id<JavaUtilSet>)createEntrySet;

- (id<JavaUtilIterator>)entryIterator;

- (id<JavaUtilNavigableMap>)forward;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMaps_DescendingMap)

FOUNDATION_EXPORT void ComGoogleCommonCollectMaps_DescendingMap_init(ComGoogleCommonCollectMaps_DescendingMap *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMaps_DescendingMap)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectMaps")
