//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:../java_deps/build_result/guava-19.0-sources.jar!com/google/common/collect/TreeMultimap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectTreeMultimap")
#ifdef RESTRICT_ComGoogleCommonCollectTreeMultimap
#define INCLUDE_ALL_ComGoogleCommonCollectTreeMultimap 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectTreeMultimap 1
#endif
#undef RESTRICT_ComGoogleCommonCollectTreeMultimap

#if !defined (ComGoogleCommonCollectTreeMultimap_) && (INCLUDE_ALL_ComGoogleCommonCollectTreeMultimap || defined(INCLUDE_ComGoogleCommonCollectTreeMultimap))
#define ComGoogleCommonCollectTreeMultimap_

#define RESTRICT_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap 1
#define INCLUDE_ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap 1
#include "com/google/common/collect/AbstractSortedKeySortedSetMultimap.h"

@protocol ComGoogleCommonCollectMultimap;
@protocol JavaUtilCollection;
@protocol JavaUtilComparator;
@protocol JavaUtilNavigableMap;
@protocol JavaUtilNavigableSet;
@protocol JavaUtilSortedSet;

@interface ComGoogleCommonCollectTreeMultimap : ComGoogleCommonCollectAbstractSortedKeySortedSetMultimap

#pragma mark Public

- (id<JavaUtilNavigableMap>)asMap;

+ (ComGoogleCommonCollectTreeMultimap *)create;

+ (ComGoogleCommonCollectTreeMultimap *)createWithJavaUtilComparator:(id<JavaUtilComparator>)keyComparator
                                              withJavaUtilComparator:(id<JavaUtilComparator>)valueComparator;

+ (ComGoogleCommonCollectTreeMultimap *)createWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

- (id<JavaUtilNavigableSet>)getWithId:(id)key;

- (id<JavaUtilComparator>)keyComparator;

- (id<JavaUtilNavigableSet>)keySet;

- (id<JavaUtilComparator>)valueComparator;

#pragma mark Package-Private

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)keyComparator
                    withJavaUtilComparator:(id<JavaUtilComparator>)valueComparator;

- (id<JavaUtilNavigableMap>)backingMap;

- (id<JavaUtilNavigableMap>)createAsMap;

- (id<JavaUtilSortedSet>)createCollection;

- (id<JavaUtilCollection>)createCollectionWithId:(id)key;

- (id<JavaUtilNavigableSet>)createKeySet;

- (id<JavaUtilCollection>)unmodifiableCollectionSubclassWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (id<JavaUtilCollection>)wrapCollectionWithId:(id)key
                        withJavaUtilCollection:(id<JavaUtilCollection>)collection;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectTreeMultimap)

FOUNDATION_EXPORT ComGoogleCommonCollectTreeMultimap *ComGoogleCommonCollectTreeMultimap_create();

FOUNDATION_EXPORT ComGoogleCommonCollectTreeMultimap *ComGoogleCommonCollectTreeMultimap_createWithJavaUtilComparator_withJavaUtilComparator_(id<JavaUtilComparator> keyComparator, id<JavaUtilComparator> valueComparator);

FOUNDATION_EXPORT ComGoogleCommonCollectTreeMultimap *ComGoogleCommonCollectTreeMultimap_createWithComGoogleCommonCollectMultimap_(id<ComGoogleCommonCollectMultimap> multimap);

FOUNDATION_EXPORT void ComGoogleCommonCollectTreeMultimap_initWithJavaUtilComparator_withJavaUtilComparator_(ComGoogleCommonCollectTreeMultimap *self, id<JavaUtilComparator> keyComparator, id<JavaUtilComparator> valueComparator);

FOUNDATION_EXPORT ComGoogleCommonCollectTreeMultimap *new_ComGoogleCommonCollectTreeMultimap_initWithJavaUtilComparator_withJavaUtilComparator_(id<JavaUtilComparator> keyComparator, id<JavaUtilComparator> valueComparator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectTreeMultimap *create_ComGoogleCommonCollectTreeMultimap_initWithJavaUtilComparator_withJavaUtilComparator_(id<JavaUtilComparator> keyComparator, id<JavaUtilComparator> valueComparator);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectTreeMultimap)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectTreeMultimap")
