//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/x509/GeneralSubtree.java
//

#ifndef _OrgApacheHarmonySecurityX509GeneralSubtree_H_
#define _OrgApacheHarmonySecurityX509GeneralSubtree_H_

#include "../../../../../J2ObjC_header.h"

@class IOSByteArray;
@class JavaLangStringBuilder;
@class OrgApacheHarmonySecurityAsn1ASN1Sequence;
@class OrgApacheHarmonySecurityX509GeneralName;

/*!
 @author Vladimir N. Molotkov, Alexander Y. Kleymenov
 @version $Revision$
 */

/*!
 @brief The class encapsulates the ASN.1 DER encoding/decoding work
 with the GeneralSubtree structure which is a part of X.509 certificate:
 (as specified in RFC 3280 -
 Internet X.509 Public Key Infrastructure.
 Certificate and Certificate Revocation List (CRL) Profile.
 http://www.ietf.org/rfc/rfc3280.txt):
 @code

   GeneralSubtree ::= SEQUENCE {
        base                    GeneralName,
        minimum         [0]     BaseDistance DEFAULT 0,
        maximum         [1]     BaseDistance OPTIONAL }
   BaseDistance ::= INTEGER (0..MAX)
  
@endcode
 */
@interface OrgApacheHarmonySecurityX509GeneralSubtree : NSObject

#pragma mark Public

- (instancetype)initWithOrgApacheHarmonySecurityX509GeneralName:(OrgApacheHarmonySecurityX509GeneralName *)base
                                                        withInt:(jint)minimum
                                                        withInt:(jint)maximum;

- (void)dumpValueWithJavaLangStringBuilder:(JavaLangStringBuilder *)sb
                              withNSString:(NSString *)prefix;

/*!
 @brief Returns the value of base field of the structure.
 */
- (OrgApacheHarmonySecurityX509GeneralName *)getBase;

/*!
 @brief Returns ASN.1 encoded form of this X.509 GeneralSubtree value.
 */
- (IOSByteArray *)getEncoded;

@end

J2OBJC_STATIC_INIT(OrgApacheHarmonySecurityX509GeneralSubtree)

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1ASN1Sequence *OrgApacheHarmonySecurityX509GeneralSubtree_ASN1_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonySecurityX509GeneralSubtree, ASN1_, OrgApacheHarmonySecurityAsn1ASN1Sequence *)

FOUNDATION_EXPORT void OrgApacheHarmonySecurityX509GeneralSubtree_initWithOrgApacheHarmonySecurityX509GeneralName_withInt_withInt_(OrgApacheHarmonySecurityX509GeneralSubtree *self, OrgApacheHarmonySecurityX509GeneralName *base, jint minimum, jint maximum);

FOUNDATION_EXPORT OrgApacheHarmonySecurityX509GeneralSubtree *new_OrgApacheHarmonySecurityX509GeneralSubtree_initWithOrgApacheHarmonySecurityX509GeneralName_withInt_withInt_(OrgApacheHarmonySecurityX509GeneralName *base, jint minimum, jint maximum) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityX509GeneralSubtree)

#endif // _OrgApacheHarmonySecurityX509GeneralSubtree_H_
