//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/utils/WrappedX509Certificate.java
//

#ifndef _OrgApacheHarmonySecurityUtilsWrappedX509Certificate_H_
#define _OrgApacheHarmonySecurityUtilsWrappedX509Certificate_H_

#include "../../../../../J2ObjC_header.h"
#include "../../../../../java/security/cert/X509Certificate.h"

@class IOSBooleanArray;
@class IOSByteArray;
@class JavaMathBigInteger;
@class JavaUtilDate;
@protocol JavaSecurityPrincipal;
@protocol JavaSecurityPublicKey;
@protocol JavaUtilSet;

@interface OrgApacheHarmonySecurityUtilsWrappedX509Certificate : JavaSecurityCertX509Certificate

#pragma mark Public

- (instancetype)initWithJavaSecurityCertX509Certificate:(JavaSecurityCertX509Certificate *)wrapped;

- (void)checkValidity;

- (void)checkValidityWithJavaUtilDate:(JavaUtilDate *)date;

- (jint)getBasicConstraints;

- (id<JavaUtilSet>)getCriticalExtensionOIDs;

- (IOSByteArray *)getEncoded;

- (IOSByteArray *)getExtensionValueWithNSString:(NSString *)oid;

- (id<JavaSecurityPrincipal>)getIssuerDN;

- (IOSBooleanArray *)getIssuerUniqueID;

- (IOSBooleanArray *)getKeyUsage;

- (id<JavaUtilSet>)getNonCriticalExtensionOIDs;

- (JavaUtilDate *)getNotAfter;

- (JavaUtilDate *)getNotBefore;

- (id<JavaSecurityPublicKey>)getPublicKey;

- (JavaMathBigInteger *)getSerialNumber;

- (NSString *)getSigAlgName;

- (NSString *)getSigAlgOID;

- (IOSByteArray *)getSigAlgParams;

- (IOSByteArray *)getSignature;

- (id<JavaSecurityPrincipal>)getSubjectDN;

- (IOSBooleanArray *)getSubjectUniqueID;

- (IOSByteArray *)getTBSCertificate;

- (jint)getVersion;

- (jboolean)hasUnsupportedCriticalExtension;

- (NSString *)description;

- (void)verifyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)key;

- (void)verifyWithJavaSecurityPublicKey:(id<JavaSecurityPublicKey>)key
                           withNSString:(NSString *)sigProvider;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheHarmonySecurityUtilsWrappedX509Certificate)

FOUNDATION_EXPORT void OrgApacheHarmonySecurityUtilsWrappedX509Certificate_initWithJavaSecurityCertX509Certificate_(OrgApacheHarmonySecurityUtilsWrappedX509Certificate *self, JavaSecurityCertX509Certificate *wrapped);

FOUNDATION_EXPORT OrgApacheHarmonySecurityUtilsWrappedX509Certificate *new_OrgApacheHarmonySecurityUtilsWrappedX509Certificate_initWithJavaSecurityCertX509Certificate_(JavaSecurityCertX509Certificate *wrapped) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityUtilsWrappedX509Certificate)

#endif // _OrgApacheHarmonySecurityUtilsWrappedX509Certificate_H_
