//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/net/ssl/ManagerFactoryParameters.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaxNetSslManagerFactoryParameters")
#ifdef RESTRICT_JavaxNetSslManagerFactoryParameters
#define INCLUDE_ALL_JavaxNetSslManagerFactoryParameters 0
#else
#define INCLUDE_ALL_JavaxNetSslManagerFactoryParameters 1
#endif
#undef RESTRICT_JavaxNetSslManagerFactoryParameters

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (JavaxNetSslManagerFactoryParameters_) && (INCLUDE_ALL_JavaxNetSslManagerFactoryParameters || defined(INCLUDE_JavaxNetSslManagerFactoryParameters))
#define JavaxNetSslManagerFactoryParameters_

/*!
 @brief The marker interface for key manager factory parameters.
 Its purpose is to
 group key manager factory parameters objects.
 @since 1.4
 */
@protocol JavaxNetSslManagerFactoryParameters < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxNetSslManagerFactoryParameters)

J2OBJC_TYPE_LITERAL_HEADER(JavaxNetSslManagerFactoryParameters)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_JavaxNetSslManagerFactoryParameters")
