//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/net/ssl/TrustManager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaxNetSslTrustManager")
#ifdef RESTRICT_JavaxNetSslTrustManager
#define INCLUDE_ALL_JavaxNetSslTrustManager 0
#else
#define INCLUDE_ALL_JavaxNetSslTrustManager 1
#endif
#undef RESTRICT_JavaxNetSslTrustManager

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (JavaxNetSslTrustManager_) && (INCLUDE_ALL_JavaxNetSslTrustManager || defined(INCLUDE_JavaxNetSslTrustManager))
#define JavaxNetSslTrustManager_

/*!
 @brief The marker interface for JSSE trust managers.
 The purpose is to group trust
 managers. The responsibility a trust manager is to handle the trust data used to
 make trust decisions for deciding whether credentials of a peer should be
 accepted,
 - seealso: TrustManagerFactory
 */
@protocol JavaxNetSslTrustManager < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxNetSslTrustManager)

J2OBJC_TYPE_LITERAL_HEADER(JavaxNetSslTrustManager)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_JavaxNetSslTrustManager")
